// Code generated by mapdb-codegen. DO NOT EDIT.

const std = @import("std");
const Allocator = std.mem.Allocator;

/// Double-ended queue of `f32` values, backed by an `ArrayListUnmanaged`.
/// Back operations (addLast, removeLast) are O(1) amortized.
/// Front operations (addFirst, removeFirst) are O(n) due to shifting.
pub const F32ArrayDeque = struct {
    items: std.ArrayListUnmanaged(f32) = .empty,
    allocator: Allocator,

    pub fn init(allocator: Allocator) F32ArrayDeque {
        return .{ .allocator = allocator };
    }

    pub fn deinit(self: *F32ArrayDeque) void {
        self.items.deinit(self.allocator);
    }

    pub fn of(allocator: Allocator, values: []const f32) F32ArrayDeque {
        var d = init(allocator);
        d.items.appendSlice(d.allocator, values) catch @panic("out of memory");
        return d;
    }

    /// Adds a value to the front of the deque. O(n) due to shift.
    pub fn addFirst(self: *F32ArrayDeque, value: f32) void {
        self.items.insert(self.allocator, 0, value) catch @panic("out of memory");
    }

    /// Adds a value to the back of the deque. O(1) amortized.
    pub fn addLast(self: *F32ArrayDeque, value: f32) void {
        self.items.append(self.allocator, value) catch @panic("out of memory");
    }

    /// Removes and returns the front element, or null if empty. O(n).
    pub fn removeFirst(self: *F32ArrayDeque) ?f32 {
        if (self.items.items.len == 0) return null;
        return self.items.orderedRemove(0);
    }

    /// Removes and returns the back element, or null if empty. O(1).
    pub fn removeLast(self: *F32ArrayDeque) ?f32 {
        return self.items.pop();
    }

    /// Returns the front element without removing it, or null if empty.
    pub fn peekFirst(self: *const F32ArrayDeque) ?f32 {
        if (self.items.items.len == 0) return null;
        return self.items.items[0];
    }

    /// Returns the back element without removing it, or null if empty.
    pub fn peekLast(self: *const F32ArrayDeque) ?f32 {
        if (self.items.items.len == 0) return null;
        return self.items.items[self.items.items.len - 1];
    }

    pub fn len(self: *const F32ArrayDeque) usize {
        return self.items.items.len;
    }
    pub fn isEmpty(self: *const F32ArrayDeque) bool {
        return self.items.items.len == 0;
    }
    pub fn clear(self: *F32ArrayDeque) void {
        self.items.clearRetainingCapacity();
    }

    /// Ensures capacity for `additional` more items.
    pub fn ensureUnusedCapacity(self: *F32ArrayDeque, additional: usize) Allocator.Error!void {
        try self.items.ensureUnusedCapacity(self.allocator, additional);
    }

    pub fn contains(self: *const F32ArrayDeque, value: f32) bool {
        for (self.items.items) |v| {
            if (@as(u32, @bitCast(v)) == @as(u32, @bitCast(value))) return true;
        }
        return false;
    }

    /// Returns a slice view of the items in front-to-back order. Valid until
    /// the next mutation.
    pub fn slice(self: *const F32ArrayDeque) []const f32 {
        return self.items.items;
    }

    /// Returns an owned copy of the items in front-to-back order. Caller frees.
    pub fn toOwnedSlice(self: *const F32ArrayDeque, allocator: Allocator) []f32 {
        const out = allocator.alloc(f32, self.items.items.len) catch @panic("out of memory");
        @memcpy(out, self.items.items);
        return out;
    }

    pub fn forEach(self: *const F32ArrayDeque, f: *const fn (f32) void) void {
        for (self.items.items) |value| f(value);
    }

    pub fn anySatisfy(self: *const F32ArrayDeque, predicate: *const fn (f32) bool) bool {
        for (self.items.items) |value| {
            if (predicate(value)) return true;
        }
        return false;
    }

    pub fn allSatisfy(self: *const F32ArrayDeque, predicate: *const fn (f32) bool) bool {
        for (self.items.items) |value| {
            if (!predicate(value)) return false;
        }
        return true;
    }

    pub fn eql(self: *const F32ArrayDeque, other: *const F32ArrayDeque) bool {
        if (self.items.items.len != other.items.items.len) return false;
        for (self.items.items, other.items.items) |a, b| {
            if (!(@as(u32, @bitCast(a)) == @as(u32, @bitCast(b)))) return false;
        }
        return true;
    }

    pub fn format(self: *const F32ArrayDeque, comptime _: []const u8, _: std.fmt.FormatOptions, writer: anytype) !void {
        try writer.writeAll("[");
        for (self.items.items, 0..) |value, i| {
            if (i > 0) try writer.writeAll(", ");
            try std.fmt.formatType(value, "", .{}, writer, 0);
        }
        try writer.writeAll("]");
    }
};

test "F32ArrayDeque: addLast removeFirst FIFO" {
    var d = F32ArrayDeque.init(std.testing.allocator);
    defer d.deinit();
    d.addLast(1.0);
    d.addLast(2.0);
    d.addLast(3.0);
    try std.testing.expectEqual(@as(usize, 3), d.len());
    try std.testing.expectEqual(@as(?f32, 1.0), d.removeFirst());
    try std.testing.expectEqual(@as(?f32, 2.0), d.removeFirst());
    try std.testing.expectEqual(@as(?f32, 3.0), d.removeFirst());
    try std.testing.expect(d.isEmpty());
}

test "F32ArrayDeque: addFirst removeLast" {
    var d = F32ArrayDeque.init(std.testing.allocator);
    defer d.deinit();
    d.addFirst(1.0);
    d.addFirst(2.0);
    d.addFirst(3.0);
    try std.testing.expectEqual(@as(?f32, 3.0), d.peekFirst());
    try std.testing.expectEqual(@as(?f32, 1.0), d.peekLast());
    try std.testing.expectEqual(@as(?f32, 1.0), d.removeLast());
    try std.testing.expectEqual(@as(?f32, 2.0), d.removeLast());
    try std.testing.expectEqual(@as(?f32, 3.0), d.removeLast());
}

test "F32ArrayDeque: remove empty" {
    var d = F32ArrayDeque.init(std.testing.allocator);
    defer d.deinit();
    try std.testing.expectEqual(@as(?f32, null), d.removeFirst());
    try std.testing.expectEqual(@as(?f32, null), d.removeLast());
    try std.testing.expectEqual(@as(?f32, null), d.peekFirst());
    try std.testing.expectEqual(@as(?f32, null), d.peekLast());
}

test "F32ArrayDeque: mixed ops" {
    var d = F32ArrayDeque.init(std.testing.allocator);
    defer d.deinit();
    d.addLast(2.0);
    d.addFirst(1.0);
    d.addLast(3.0);
    try std.testing.expectEqual(@as(?f32, 1.0), d.removeFirst());
    try std.testing.expectEqual(@as(?f32, 3.0), d.removeLast());
    try std.testing.expectEqual(@as(?f32, 2.0), d.removeFirst());
}

test "F32ArrayDeque: contains and clear" {
    var d = F32ArrayDeque.init(std.testing.allocator);
    defer d.deinit();
    d.addLast(1.0);
    d.addLast(2.0);
    try std.testing.expect(d.contains(1.0));
    try std.testing.expect(d.contains(2.0));
    d.clear();
    try std.testing.expect(d.isEmpty());
}

test "F32ArrayDeque: toOwnedSlice" {
    var d = F32ArrayDeque.init(std.testing.allocator);
    defer d.deinit();
    d.addLast(1.0);
    d.addLast(2.0);
    d.addLast(3.0);
    const out = d.toOwnedSlice(std.testing.allocator);
    defer std.testing.allocator.free(out);
    try std.testing.expectEqual(@as(usize, 3), out.len);
}

test "F32ArrayDeque: eql" {
    var d1 = F32ArrayDeque.init(std.testing.allocator);
    defer d1.deinit();
    var d2 = F32ArrayDeque.init(std.testing.allocator);
    defer d2.deinit();
    d1.addLast(1.0);
    d1.addLast(2.0);
    d2.addLast(1.0);
    d2.addLast(2.0);
    try std.testing.expect(d1.eql(&d2));
}
