// Code generated by mapdb-codegen. DO NOT EDIT.

const std = @import("std");
const Allocator = std.mem.Allocator;
const AllocatorConfig = @import("../allocator_config.zig").AllocatorConfig;

/// Sorted map from `bool` keys to `f64` values, backed by sorted ArrayLists.
pub const BoolF64TreeMap = struct {
    keys: std.ArrayListUnmanaged(bool) = .empty,
    vals: std.ArrayListUnmanaged(f64) = .empty,
    config: AllocatorConfig,

    pub fn init(allocator: Allocator) BoolF64TreeMap {
        return .{ .config = AllocatorConfig.init(allocator) };
    }

    pub fn initWithConfig(config: AllocatorConfig) BoolF64TreeMap {
        return .{ .config = config };
    }

    pub fn deinit(self: *BoolF64TreeMap) void {
        self.keys.deinit(self.config.keysAllocator());
        self.vals.deinit(self.config.valuesAllocator());
    }

    fn orderFn(a: bool, b: bool) std.math.Order {
        return if (a == b) std.math.Order.eq else if (!a and b) std.math.Order.lt else std.math.Order.gt;
    }

    fn findIndex(self: *const BoolF64TreeMap, key: bool) struct { index: usize, found: bool } {
        var lo: usize = 0;
        var hi: usize = self.keys.items.len;
        while (lo < hi) {
            const mid = lo + (hi - lo) / 2;
            const ord = orderFn(self.keys.items[mid], key);
            if (ord == .lt) {
                lo = mid + 1;
            } else if (ord == .gt) {
                hi = mid;
            } else {
                return .{ .index = mid, .found = true };
            }
        }
        return .{ .index = lo, .found = false };
    }

    /// Inserts a key-value pair. Returns the old value if the key existed.
    pub fn put(self: *BoolF64TreeMap, key: bool, value: f64) ?f64 {
        const result = self.findIndex(key);
        if (result.found) {
            const old = self.vals.items[result.index];
            self.vals.items[result.index] = value;
            return old;
        }
        self.keys.insert(self.config.keysAllocator(), result.index, key) catch @panic("out of memory");
        self.vals.insert(self.config.valuesAllocator(), result.index, value) catch @panic("out of memory");
        return null;
    }

    pub fn get(self: *const BoolF64TreeMap, key: bool) ?f64 {
        const result = self.findIndex(key);
        if (!result.found) return null;
        return self.vals.items[result.index];
    }

    pub fn remove(self: *BoolF64TreeMap, key: bool) ?f64 {
        const result = self.findIndex(key);
        if (!result.found) return null;
        const old = self.vals.items[result.index];
        _ = self.keys.orderedRemove(result.index);
        _ = self.vals.orderedRemove(result.index);
        return old;
    }

    pub fn containsKey(self: *const BoolF64TreeMap, key: bool) bool {
        return self.findIndex(key).found;
    }

    pub fn getOrDefault(self: *const BoolF64TreeMap, key: bool, default_value: f64) f64 {
        return self.get(key) orelse default_value;
    }

    pub fn len(self: *const BoolF64TreeMap) usize {
        return self.keys.items.len;
    }

    /// Alias for len() — matches Go/Java naming.
    pub fn size(self: *const BoolF64TreeMap) usize {
        return self.len();
    }

    pub fn isEmpty(self: *const BoolF64TreeMap) bool {
        return self.keys.items.len == 0;
    }

    pub fn clear(self: *BoolF64TreeMap) void {
        self.keys.clearRetainingCapacity();
        self.vals.clearRetainingCapacity();
    }

    // ---- Fallible capacity reservation ----

    /// Ensures both the keys and values buffers can hold `additional` more
    /// entries without reallocating. Returns `error.OutOfMemory` if the
    /// allocator fails.
    pub fn ensureUnusedCapacity(self: *BoolF64TreeMap, additional: usize) Allocator.Error!void {
        try self.keys.ensureUnusedCapacity(self.config.keysAllocator(), additional);
        try self.vals.ensureUnusedCapacity(self.config.valuesAllocator(), additional);
    }

    /// Ensures both internal buffers' total capacity is at least
    /// `new_capacity`.
    pub fn ensureTotalCapacity(self: *BoolF64TreeMap, new_capacity: usize) Allocator.Error!void {
        try self.keys.ensureTotalCapacity(self.config.keysAllocator(), new_capacity);
        try self.vals.ensureTotalCapacity(self.config.valuesAllocator(), new_capacity);
    }

    pub fn min(self: *const BoolF64TreeMap) ?struct { key: bool, value: f64 } {
        if (self.keys.items.len == 0) return null;
        return .{ .key = self.keys.items[0], .value = self.vals.items[0] };
    }

    pub fn max(self: *const BoolF64TreeMap) ?struct { key: bool, value: f64 } {
        if (self.keys.items.len == 0) return null;
        const last = self.keys.items.len - 1;
        return .{ .key = self.keys.items[last], .value = self.vals.items[last] };
    }

    pub fn keysSlice(self: *const BoolF64TreeMap) []const bool {
        return self.keys.items;
    }

    pub fn valuesSlice(self: *const BoolF64TreeMap) []const f64 {
        return self.vals.items;
    }

    // ---- Iteration ----

    pub fn forEach(self: *const BoolF64TreeMap, f: *const fn (bool, f64) void) void {
        for (self.keys.items, self.vals.items) |k, val| f(k, val);
    }

    pub fn forEachKey(self: *const BoolF64TreeMap, f: *const fn (bool) void) void {
        for (self.keys.items) |k| f(k);
    }

    pub fn forEachValue(self: *const BoolF64TreeMap, f: *const fn (f64) void) void {
        for (self.vals.items) |val| f(val);
    }

    // ---- Functional Operations ----

    pub fn select(self: *const BoolF64TreeMap, predicate: *const fn (bool, f64) bool) BoolF64TreeMap {
        var result = init(self.config.base);
        for (self.keys.items, self.vals.items) |k, val| {
            if (predicate(k, val)) _ = result.put(k, val);
        }
        return result;
    }

    pub fn reject(self: *const BoolF64TreeMap, predicate: *const fn (bool, f64) bool) BoolF64TreeMap {
        var result = init(self.config.base);
        for (self.keys.items, self.vals.items) |k, val| {
            if (!predicate(k, val)) _ = result.put(k, val);
        }
        return result;
    }

    pub fn detect(self: *const BoolF64TreeMap, predicate: *const fn (bool, f64) bool) ?struct { key: bool, value: f64 } {
        for (self.keys.items, self.vals.items) |k, val| {
            if (predicate(k, val)) return .{ .key = k, .value = val };
        }
        return null;
    }

    pub fn anySatisfy(self: *const BoolF64TreeMap, predicate: *const fn (bool, f64) bool) bool {
        for (self.keys.items, self.vals.items) |k, val| {
            if (predicate(k, val)) return true;
        }
        return false;
    }

    pub fn allSatisfy(self: *const BoolF64TreeMap, predicate: *const fn (bool, f64) bool) bool {
        for (self.keys.items, self.vals.items) |k, val| {
            if (!predicate(k, val)) return false;
        }
        return true;
    }

    pub fn noneSatisfy(self: *const BoolF64TreeMap, predicate: *const fn (bool, f64) bool) bool {
        for (self.keys.items, self.vals.items) |k, val| {
            if (predicate(k, val)) return false;
        }
        return true;
    }

    pub fn count(self: *const BoolF64TreeMap, predicate: *const fn (bool, f64) bool) usize {
        var c: usize = 0;
        for (self.keys.items, self.vals.items) |k, val| {
            if (predicate(k, val)) c += 1;
        }
        return c;
    }

    // ---- Range Operations ----

    /// Returns the entry with the smallest key >= the given key, or null.
    pub fn ceiling(self: *const BoolF64TreeMap, key: bool) ?struct { key: bool, value: f64 } {
        const result = self.findIndex(key);
        if (result.found) return .{ .key = self.keys.items[result.index], .value = self.vals.items[result.index] };
        if (result.index < self.keys.items.len) return .{ .key = self.keys.items[result.index], .value = self.vals.items[result.index] };
        return null;
    }

    /// Returns the entry with the largest key <= the given key, or null.
    pub fn floor(self: *const BoolF64TreeMap, key: bool) ?struct { key: bool, value: f64 } {
        const result = self.findIndex(key);
        if (result.found) return .{ .key = self.keys.items[result.index], .value = self.vals.items[result.index] };
        if (result.index > 0) return .{ .key = self.keys.items[result.index - 1], .value = self.vals.items[result.index - 1] };
        return null;
    }

    /// Returns keys in [from, to] inclusive as a slice view.
    pub fn rangeKeys(self: *const BoolF64TreeMap, from: bool, to: bool) []const bool {
        const lo = self.findIndex(from).index;
        var hi = lo;
        while (hi < self.keys.items.len) {
            if (orderFn(self.keys.items[hi], to) == .gt) break;
            hi += 1;
        }
        if (lo >= hi) return self.keys.items[0..0];
        return self.keys.items[lo..hi];
    }

    // ---- Formatting ----

    /// Formats as "{k1=v1, k2=v2}" in sorted key order.
    pub fn format(self: *const BoolF64TreeMap, comptime _: []const u8, _: std.fmt.FormatOptions, writer: anytype) !void {
        try writer.writeAll("{");
        for (self.keys.items, self.vals.items, 0..) |k, v, i| {
            if (i > 0) try writer.writeAll(", ");
            try std.fmt.formatType(k, "", .{}, writer, 0);
            try writer.writeAll("=");
            try std.fmt.formatType(v, "", .{}, writer, 0);
        }
        try writer.writeAll("}");
    }

    // ---- Fluent API ----

    pub fn withKeyValue(self: *BoolF64TreeMap, key: bool, value: f64) *BoolF64TreeMap {
        _ = self.put(key, value);
        return self;
    }

    pub fn withoutKey(self: *BoolF64TreeMap, key: bool) *BoolF64TreeMap {
        _ = self.remove(key);
        return self;
    }

    // ---- Equality ----

    pub fn eql(self: *const BoolF64TreeMap, other: *const BoolF64TreeMap) bool {
        if (self.keys.items.len != other.keys.items.len) return false;
        for (self.keys.items, self.vals.items, other.keys.items, other.vals.items) |k1, v1, k2, v2| {
            if (!(k1 == k2)) return false;
            if (!(@as(u64, @bitCast(v1)) == @as(u64, @bitCast(v2)))) return false;
        }
        return true;
    }
};

test "BoolF64TreeMap: put and get" {
    var m = BoolF64TreeMap.init(std.testing.allocator);
    defer m.deinit();
    _ = m.put(true, 1.0);
    _ = m.put(false, 2.0);

    try std.testing.expectEqual(@as(usize, 2), m.len());
    try std.testing.expectEqual(@as(?f64, 1.0), m.get(true));
}

test "BoolF64TreeMap: sorted keys" {
    var m = BoolF64TreeMap.init(std.testing.allocator);
    defer m.deinit();
    _ = m.put(true, 1.0);
    _ = m.put(false, 2.0);
    try std.testing.expectEqual(@as(usize, 2), m.len());
}

test "BoolF64TreeMap: min max" {
    var m = BoolF64TreeMap.init(std.testing.allocator);
    defer m.deinit();
    _ = m.put(true, 1.0);
    _ = m.put(false, 2.0);
    try std.testing.expect(m.min() != null);
    try std.testing.expect(m.max() != null);
}

test "BoolF64TreeMap: remove" {
    var m = BoolF64TreeMap.init(std.testing.allocator);
    defer m.deinit();
    _ = m.put(true, 1.0);
    _ = m.put(false, 2.0);
    const removed = m.remove(true);
    try std.testing.expectEqual(@as(?f64, 1.0), removed);
    try std.testing.expectEqual(@as(usize, 1), m.len());
}

test "BoolF64TreeMap: clear" {
    var m = BoolF64TreeMap.init(std.testing.allocator);
    defer m.deinit();
    _ = m.put(true, 1.0);
    m.clear();
    try std.testing.expect(m.isEmpty());
}

test "BoolF64TreeMap: eql" {
    var m1 = BoolF64TreeMap.init(std.testing.allocator);
    defer m1.deinit();
    _ = m1.put(true, 1.0);
    _ = m1.put(false, 2.0);

    var m2 = BoolF64TreeMap.init(std.testing.allocator);
    defer m2.deinit();
    _ = m2.put(false, 2.0);
    _ = m2.put(true, 1.0);
    try std.testing.expect(m1.eql(&m2));
}

test "BoolF64TreeMap: ensureUnusedCapacity reserves both buffers" {
    var m = BoolF64TreeMap.init(std.testing.allocator);
    defer m.deinit();
    try m.ensureUnusedCapacity(100);
    const kcap = m.keys.capacity;
    const vcap = m.vals.capacity;
    try std.testing.expect(kcap >= 100);
    try std.testing.expect(vcap >= 100);
    _ = m.put(true, 1.0);
    _ = m.put(false, 2.0);
    try std.testing.expectEqual(kcap, m.keys.capacity);
    try std.testing.expectEqual(vcap, m.vals.capacity);
}

test "BoolF64TreeMap: ensureUnusedCapacity propagates allocator error" {
    // fail_index = 0: TreeMap.init doesn't allocate (Treap is node-based),
    // so the first alloc (ensureUnusedCapacity grow) fails immediately.
    var failing = std.testing.FailingAllocator.init(std.testing.allocator, .{ .fail_index = 0 });
    var m = BoolF64TreeMap.init(failing.allocator());
    defer m.deinit();
    try std.testing.expectError(error.OutOfMemory, m.ensureUnusedCapacity(1024));
}
