// Code generated by mapdb-codegen. DO NOT EDIT.

const std = @import("std");
const Allocator = std.mem.Allocator;
const AllocatorConfig = @import("../allocator_config.zig").AllocatorConfig;
const OpenHashMap = @import("../hash_table.zig").OpenHashMap;
const ImmutableBoolCharHashMap = @import("../immutable/immutable_bool_char_hash_map.zig").ImmutableBoolCharHashMap;

/// Hash map from `bool` keys to `u21` values.
///
/// Custom open-addressing with linear probing and Robin Hood backward-shift deletion.
/// Supports separate allocators for keys, values, and index buckets via AllocatorConfig.
pub const BoolCharHashMap = struct {
    inner: OpenHashMap(bool, u21),
    config: AllocatorConfig,

    // ---- Construction / Destruction ----

    pub fn init(allocator: Allocator) BoolCharHashMap {
        return initWithConfig(AllocatorConfig.init(allocator));
    }

    /// Create with pre-allocated capacity.
    pub fn initWithCapacity(allocator: Allocator, capacity: usize) BoolCharHashMap {
        return .{
            .inner = OpenHashMap(bool, u21).initCapacity(allocator, capacity) catch @panic("out of memory"),
            .config = AllocatorConfig.init(allocator),
        };
    }

    /// Create with fine-grained allocator control.
    pub fn initWithConfig(config: AllocatorConfig) BoolCharHashMap {
        return .{
            .inner = OpenHashMap(bool, u21).init(
                config.keysAllocator(),
                config.valuesAllocator(),
                config.indexAllocator(),
            ) catch @panic("out of memory"),
            .config = config,
        };
    }

    pub fn deinit(self: *BoolCharHashMap) void {
        self.inner.deinit();
    }

    // ---- Core Operations ----

    /// Inserts a key-value pair. Returns the old value if the key was already present.
    pub fn put(self: *BoolCharHashMap, key: bool, value: u21) ?u21 {
        return self.inner.put(key, value) catch @panic("out of memory");
    }

    /// Returns the value for the key, or null.
    pub fn get(self: *const BoolCharHashMap, key: bool) ?u21 {
        return self.inner.get(key);
    }

    /// Returns the value for the key, or the default.
    pub fn getOrDefault(self: *const BoolCharHashMap, key: bool, default_value: u21) u21 {
        return self.get(key) orelse default_value;
    }

    /// Removes the key. Returns the old value if present.
    pub fn remove(self: *BoolCharHashMap, key: bool) ?u21 {
        return self.inner.remove(key);
    }

    pub fn containsKey(self: *const BoolCharHashMap, key: bool) bool {
        return self.inner.containsKey(key);
    }

    pub fn containsValue(self: *const BoolCharHashMap, value: u21) bool {
        return self.inner.containsValue(value);
    }

    // ---- Entry API ----

    /// Entry provides atomic check-and-modify operations for a single key.
    pub const Entry = struct {
        map_ptr: *BoolCharHashMap,
        key: bool,

        /// Inserts the default value if the key is absent. Returns the current value.
        pub fn orInsert(self: Entry, default_value: u21) u21 {
            if (self.map_ptr.get(self.key)) |existing| return existing;
            _ = self.map_ptr.put(self.key, default_value);
            return default_value;
        }

        /// Inserts the value from the function if the key is absent.
        pub fn orInsertWith(self: Entry, f: *const fn () u21) u21 {
            if (self.map_ptr.get(self.key)) |existing| return existing;
            const val = f();
            _ = self.map_ptr.put(self.key, val);
            return val;
        }

        /// Calls the function on a pointer to the value if the key is present.
        pub fn andModify(self: Entry, f: *const fn (*u21) void) Entry {
            if (self.map_ptr.inner.getPtr(self.key)) |val_ptr| {
                f(val_ptr);
            }
            return self;
        }
    };

    pub fn getEntry(self: *BoolCharHashMap, key: bool) Entry {
        return .{ .map_ptr = self, .key = key };
    }

    pub fn len(self: *const BoolCharHashMap) usize {
        return self.inner.len();
    }

    pub fn size(self: *const BoolCharHashMap) usize {
        return self.inner.len();
    }

    pub fn isEmpty(self: *const BoolCharHashMap) bool {
        return self.inner.isEmpty();
    }

    pub fn clear(self: *BoolCharHashMap) void {
        self.inner.clear();
    }

    // ---- Fallible capacity reservation ----

    /// Ensures that `additional` more entries can be put without triggering
    /// a rehash. Returns `error.OutOfMemory` if the allocator fails. See
    /// `docs/zig/error-handling.md`.
    pub fn ensureUnusedCapacity(self: *BoolCharHashMap, additional: usize) Allocator.Error!void {
        return self.inner.ensureCapacity(additional);
    }

    /// Ensures the map's total capacity can fit at least `new_capacity`
    /// entries under the load factor without a rehash.
    pub fn ensureTotalCapacity(self: *BoolCharHashMap, new_capacity: usize) Allocator.Error!void {
        if (new_capacity <= self.inner.len()) return;
        return self.inner.ensureCapacity(new_capacity - self.inner.len());
    }

    // ---- Iteration ----

    pub fn forEach(self: *const BoolCharHashMap, f: *const fn (bool, u21) void) void {
        self.inner.forEach(f);
    }

    pub fn forEachKey(self: *const BoolCharHashMap, f: *const fn (bool) void) void {
        self.inner.forEachKey(f);
    }

    pub fn forEachValue(self: *const BoolCharHashMap, f: *const fn (u21) void) void {
        self.inner.forEachValue(f);
    }

    // ---- Functional Operations ----

    pub fn select(self: *const BoolCharHashMap, predicate: *const fn (bool, u21) bool) BoolCharHashMap {
        var result = init(self.config.base);
        for (0..self.inner.capacity) |i| {
            if (self.inner.entries[i].occupied) {
                if (predicate(self.inner.entries[i].key, self.inner.entries[i].value))
                    _ = result.put(self.inner.entries[i].key, self.inner.entries[i].value);
            }
        }
        return result;
    }

    pub fn reject(self: *const BoolCharHashMap, predicate: *const fn (bool, u21) bool) BoolCharHashMap {
        var result = init(self.config.base);
        for (0..self.inner.capacity) |i| {
            if (self.inner.entries[i].occupied) {
                if (!predicate(self.inner.entries[i].key, self.inner.entries[i].value))
                    _ = result.put(self.inner.entries[i].key, self.inner.entries[i].value);
            }
        }
        return result;
    }

    pub fn detect(self: *const BoolCharHashMap, predicate: *const fn (bool, u21) bool) ?struct { key: bool, value: u21 } {
        for (0..self.inner.capacity) |i| {
            if (self.inner.entries[i].occupied) {
                if (predicate(self.inner.entries[i].key, self.inner.entries[i].value))
                    return .{ .key = self.inner.entries[i].key, .value = self.inner.entries[i].value };
            }
        }
        return null;
    }

    pub fn anySatisfy(self: *const BoolCharHashMap, predicate: *const fn (bool, u21) bool) bool {
        for (0..self.inner.capacity) |i| {
            if (self.inner.entries[i].occupied and predicate(self.inner.entries[i].key, self.inner.entries[i].value)) return true;
        }
        return false;
    }

    pub fn allSatisfy(self: *const BoolCharHashMap, predicate: *const fn (bool, u21) bool) bool {
        for (0..self.inner.capacity) |i| {
            if (self.inner.entries[i].occupied and !predicate(self.inner.entries[i].key, self.inner.entries[i].value)) return false;
        }
        return true;
    }

    pub fn noneSatisfy(self: *const BoolCharHashMap, predicate: *const fn (bool, u21) bool) bool {
        for (0..self.inner.capacity) |i| {
            if (self.inner.entries[i].occupied and predicate(self.inner.entries[i].key, self.inner.entries[i].value)) return false;
        }
        return true;
    }

    pub fn count(self: *const BoolCharHashMap, predicate: *const fn (bool, u21) bool) usize {
        var c: usize = 0;
        for (0..self.inner.capacity) |i| {
            if (self.inner.entries[i].occupied and predicate(self.inner.entries[i].key, self.inner.entries[i].value)) c += 1;
        }
        return c;
    }

    pub fn injectInto(self: *const BoolCharHashMap, initial: u21, f: *const fn (u21, bool, u21) u21) u21 {
        var acc = initial;
        for (0..self.inner.capacity) |i| {
            if (self.inner.entries[i].occupied) acc = f(acc, self.inner.entries[i].key, self.inner.entries[i].value);
        }
        return acc;
    }

    // ---- Key/Value Collection ----

    pub fn keysToSlice(self: *const BoolCharHashMap, allocator: Allocator) []bool {
        return self.inner.keysToSlice(allocator) catch @panic("out of memory");
    }

    pub fn valuesToSlice(self: *const BoolCharHashMap, allocator: Allocator) []u21 {
        return self.inner.valuesToSlice(allocator) catch @panic("out of memory");
    }

    // ---- Conversion ----

    pub fn toImmutable(self: *const BoolCharHashMap) ImmutableBoolCharHashMap {
        return ImmutableBoolCharHashMap.fromMutable(self.config.base, self);
    }

    // ---- Fluent API ----

    pub fn withKeyValue(self: *BoolCharHashMap, key: bool, value: u21) *BoolCharHashMap {
        _ = self.put(key, value);
        return self;
    }

    pub fn withoutKey(self: *BoolCharHashMap, key: bool) *BoolCharHashMap {
        _ = self.remove(key);
        return self;
    }

    pub fn withoutAllKeys(self: *BoolCharHashMap, keys: []const bool) *BoolCharHashMap {
        for (keys) |key| _ = self.remove(key);
        return self;
    }

    // ---- Mutation Helpers ----

    pub fn updateValue(self: *BoolCharHashMap, key: bool, initial: u21, f: *const fn (u21) u21) u21 {
        const current = self.get(key) orelse initial;
        const new_value = f(current);
        _ = self.put(key, new_value);
        return new_value;
    }

    // ---- Formatting ----

    pub fn format(self: *const BoolCharHashMap, comptime _: []const u8, _: std.fmt.FormatOptions, writer: anytype) !void {
        try writer.writeAll("{");
        var first = true;
        for (0..self.inner.capacity) |i| {
            if (self.inner.entries[i].occupied) {
                if (!first) try writer.writeAll(", ");
                try std.fmt.formatType(self.inner.entries[i].key, "", .{}, writer, 0);
                try writer.writeAll("=");
                try std.fmt.formatType(self.inner.entries[i].value, "", .{}, writer, 0);
                first = false;
            }
        }
        try writer.writeAll("}");
    }

    // ---- Equality ----

    pub fn eql(self: *const BoolCharHashMap, other: *const BoolCharHashMap) bool {
        if (self.len() != other.len()) return false;
        for (0..self.inner.capacity) |i| {
            if (self.inner.entries[i].occupied) {
                const other_val = other.get(self.inner.entries[i].key) orelse return false;
                if (!(self.inner.entries[i].value == other_val)) return false;
            }
        }
        return true;
    }
};

// ---- Tests ----

test "BoolCharHashMap: put and get" {
    var m = BoolCharHashMap.init(std.testing.allocator);
    defer m.deinit();
    _ = m.put(true, 'a');
    _ = m.put(false, 'b');

    try std.testing.expectEqual(@as(?u21, 'a'), m.get(true));

    try std.testing.expectEqual(@as(usize, 2), m.len());
}

test "BoolCharHashMap: put overwrite" {
    var m = BoolCharHashMap.init(std.testing.allocator);
    defer m.deinit();
    _ = m.put(true, 'a');
    const old = m.put(true, 'b');
    try std.testing.expectEqual(@as(?u21, 'a'), old);
    try std.testing.expectEqual(@as(?u21, 'b'), m.get(true));
}

test "BoolCharHashMap: remove" {
    var m = BoolCharHashMap.init(std.testing.allocator);
    defer m.deinit();
    _ = m.put(true, 'a');
    _ = m.put(false, 'b');
    const removed = m.remove(true);
    try std.testing.expectEqual(@as(?u21, 'a'), removed);
    try std.testing.expectEqual(@as(usize, 1), m.len());
    try std.testing.expect(!m.containsKey(true));
}

test "BoolCharHashMap: containsKey and containsValue" {
    var m = BoolCharHashMap.init(std.testing.allocator);
    defer m.deinit();
    _ = m.put(true, 'a');
    try std.testing.expect(m.containsKey(true));
    try std.testing.expect(!m.containsKey(false));
    try std.testing.expect(m.containsValue('a'));
    try std.testing.expect(!m.containsValue('z'));
}

test "BoolCharHashMap: getOrDefault" {
    var m = BoolCharHashMap.init(std.testing.allocator);
    defer m.deinit();
    _ = m.put(true, 'a');
    try std.testing.expectEqual('a', m.getOrDefault(true, 'c'));
    try std.testing.expectEqual('c', m.getOrDefault(false, 'c'));
}

test "BoolCharHashMap: clear" {
    var m = BoolCharHashMap.init(std.testing.allocator);
    defer m.deinit();
    _ = m.put(true, 'a');
    m.clear();
    try std.testing.expect(m.isEmpty());
}

test "BoolCharHashMap: select" {
    var m = BoolCharHashMap.init(std.testing.allocator);
    defer m.deinit();
    _ = m.put(true, 'a');
    _ = m.put(false, 'b');
    var sel = m.select(struct {
        fn f(_: bool, v: u21) bool {
            return v == 'a';
        }
    }.f);
    defer sel.deinit();
    try std.testing.expect(sel.len() >= 1);
}

test "BoolCharHashMap: keysToSlice and valuesToSlice" {
    var m = BoolCharHashMap.init(std.testing.allocator);
    defer m.deinit();
    _ = m.put(true, 'a');
    _ = m.put(false, 'b');
    const keys = m.keysToSlice(std.testing.allocator);
    defer std.testing.allocator.free(keys);
    try std.testing.expectEqual(@as(usize, 2), keys.len);
    const vals = m.valuesToSlice(std.testing.allocator);
    defer std.testing.allocator.free(vals);
    try std.testing.expectEqual(@as(usize, 2), vals.len);
}

test "BoolCharHashMap: toImmutable" {
    var m = BoolCharHashMap.init(std.testing.allocator);
    defer m.deinit();
    _ = m.put(true, 'a');
    _ = m.put(false, 'b');
    var im = m.toImmutable();
    defer im.deinit();
    try std.testing.expectEqual(@as(usize, 2), im.len());
    _ = m.put(true, 'c');
    try std.testing.expectEqual(@as(usize, 2), im.len());
}

test "BoolCharHashMap: fluent withKeyValue/withoutKey" {
    var m = BoolCharHashMap.init(std.testing.allocator);
    defer m.deinit();
    _ = m.withKeyValue(true, 'a').withKeyValue(false, 'b');
    try std.testing.expectEqual(@as(usize, 2), m.len());
    _ = m.withoutKey(true);
    try std.testing.expectEqual(@as(usize, 1), m.len());
}

test "BoolCharHashMap: eql" {
    var m1 = BoolCharHashMap.init(std.testing.allocator);
    defer m1.deinit();
    _ = m1.put(true, 'a');
    _ = m1.put(false, 'b');
    var m2 = BoolCharHashMap.init(std.testing.allocator);
    defer m2.deinit();
    _ = m2.put(false, 'b');
    _ = m2.put(true, 'a');
    try std.testing.expect(m1.eql(&m2));
}

test "BoolCharHashMap: resize" {
    var m = BoolCharHashMap.init(std.testing.allocator);
    defer m.deinit();
    var i: usize = 0;
    while (i < 50) : (i += 1) {
        _ = m.put(i % 2 == 0, @as(u21, @intCast(i % 26)) + 'A');
    }
    try std.testing.expect(m.len() > 0);
}

test "BoolCharHashMap: entry orInsert" {
    var m = BoolCharHashMap.init(std.testing.allocator);
    defer m.deinit();
    // Key absent — inserts default
    const v1 = m.getEntry(true).orInsert('a');
    try std.testing.expectEqual('a', v1);
    // Key present — returns existing
    _ = m.put(true, 'b');
    const v2 = m.getEntry(true).orInsert('c');
    try std.testing.expectEqual('b', v2);
}

test "BoolCharHashMap: entry andModify orInsert" {
    var m = BoolCharHashMap.init(std.testing.allocator);
    defer m.deinit();
    // Key absent: andModify is no-op, orInsert inserts
    _ = m.getEntry(true).andModify(struct {
        fn f(_: *u21) void {}
    }.f).orInsert('a');
    try std.testing.expectEqual(@as(?u21, 'a'), m.get(true));
}

test "BoolCharHashMap: ensureUnusedCapacity reserves and subsequent put does not resize" {
    var m = BoolCharHashMap.init(std.testing.allocator);
    defer m.deinit();
    try m.ensureUnusedCapacity(500);
    const reserved = m.inner.capacity;
    try std.testing.expect(reserved >= 500);
    _ = m.put(true, 'a');
    _ = m.put(false, 'b');
    try std.testing.expectEqual(reserved, m.inner.capacity);
}

test "BoolCharHashMap: ensureTotalCapacity is idempotent when capacity already sufficient" {
    var m = BoolCharHashMap.init(std.testing.allocator);
    defer m.deinit();
    try m.ensureTotalCapacity(500);
    const reserved = m.inner.capacity;
    try m.ensureTotalCapacity(10);
    try std.testing.expectEqual(reserved, m.inner.capacity);
}

test "BoolCharHashMap: ensureUnusedCapacity propagates allocator error" {
    // fail_index = 1: HashMap.init allocates the backing hash table (1st alloc),
    // then ensureUnusedCapacity triggers a grow that fails (2nd alloc).
    var failing = std.testing.FailingAllocator.init(std.testing.allocator, .{ .fail_index = 1 });
    var m = BoolCharHashMap.init(failing.allocator());
    defer m.deinit();
    try std.testing.expectError(error.OutOfMemory, m.ensureUnusedCapacity(10_000));
}
