// Code generated by mapdb-codegen. DO NOT EDIT.

const std = @import("std");
const Allocator = std.mem.Allocator;
const AllocatorConfig = @import("../allocator_config.zig").AllocatorConfig;
const OpenHashMap = @import("../hash_table.zig").OpenHashMap;
const ImmutableCharBoolHashMap = @import("../immutable/immutable_char_bool_hash_map.zig").ImmutableCharBoolHashMap;

/// Hash map from `u21` keys to `bool` values.
///
/// Custom open-addressing with linear probing and Robin Hood backward-shift deletion.
/// Supports separate allocators for keys, values, and index buckets via AllocatorConfig.
pub const CharBoolHashMap = struct {
    inner: OpenHashMap(u21, bool),
    config: AllocatorConfig,

    // ---- Construction / Destruction ----

    pub fn init(allocator: Allocator) CharBoolHashMap {
        return initWithConfig(AllocatorConfig.init(allocator));
    }

    /// Create with pre-allocated capacity.
    pub fn initWithCapacity(allocator: Allocator, capacity: usize) CharBoolHashMap {
        return .{
            .inner = OpenHashMap(u21, bool).initCapacity(allocator, capacity) catch @panic("out of memory"),
            .config = AllocatorConfig.init(allocator),
        };
    }

    /// Create with fine-grained allocator control.
    pub fn initWithConfig(config: AllocatorConfig) CharBoolHashMap {
        return .{
            .inner = OpenHashMap(u21, bool).init(
                config.keysAllocator(),
                config.valuesAllocator(),
                config.indexAllocator(),
            ) catch @panic("out of memory"),
            .config = config,
        };
    }

    pub fn deinit(self: *CharBoolHashMap) void {
        self.inner.deinit();
    }

    // ---- Core Operations ----

    /// Inserts a key-value pair. Returns the old value if the key was already present.
    pub fn put(self: *CharBoolHashMap, key: u21, value: bool) ?bool {
        return self.inner.put(key, value) catch @panic("out of memory");
    }

    /// Returns the value for the key, or null.
    pub fn get(self: *const CharBoolHashMap, key: u21) ?bool {
        return self.inner.get(key);
    }

    /// Returns the value for the key, or the default.
    pub fn getOrDefault(self: *const CharBoolHashMap, key: u21, default_value: bool) bool {
        return self.get(key) orelse default_value;
    }

    /// Removes the key. Returns the old value if present.
    pub fn remove(self: *CharBoolHashMap, key: u21) ?bool {
        return self.inner.remove(key);
    }

    pub fn containsKey(self: *const CharBoolHashMap, key: u21) bool {
        return self.inner.containsKey(key);
    }

    pub fn containsValue(self: *const CharBoolHashMap, value: bool) bool {
        return self.inner.containsValue(value);
    }

    // ---- Entry API ----

    /// Entry provides atomic check-and-modify operations for a single key.
    pub const Entry = struct {
        map_ptr: *CharBoolHashMap,
        key: u21,

        /// Inserts the default value if the key is absent. Returns the current value.
        pub fn orInsert(self: Entry, default_value: bool) bool {
            if (self.map_ptr.get(self.key)) |existing| return existing;
            _ = self.map_ptr.put(self.key, default_value);
            return default_value;
        }

        /// Inserts the value from the function if the key is absent.
        pub fn orInsertWith(self: Entry, f: *const fn () bool) bool {
            if (self.map_ptr.get(self.key)) |existing| return existing;
            const val = f();
            _ = self.map_ptr.put(self.key, val);
            return val;
        }

        /// Calls the function on a pointer to the value if the key is present.
        pub fn andModify(self: Entry, f: *const fn (*bool) void) Entry {
            if (self.map_ptr.inner.getPtr(self.key)) |val_ptr| {
                f(val_ptr);
            }
            return self;
        }
    };

    pub fn getEntry(self: *CharBoolHashMap, key: u21) Entry {
        return .{ .map_ptr = self, .key = key };
    }

    pub fn len(self: *const CharBoolHashMap) usize {
        return self.inner.len();
    }

    pub fn size(self: *const CharBoolHashMap) usize {
        return self.inner.len();
    }

    pub fn isEmpty(self: *const CharBoolHashMap) bool {
        return self.inner.isEmpty();
    }

    pub fn clear(self: *CharBoolHashMap) void {
        self.inner.clear();
    }

    // ---- Fallible capacity reservation ----

    /// Ensures that `additional` more entries can be put without triggering
    /// a rehash. Returns `error.OutOfMemory` if the allocator fails. See
    /// `docs/zig/error-handling.md`.
    pub fn ensureUnusedCapacity(self: *CharBoolHashMap, additional: usize) Allocator.Error!void {
        return self.inner.ensureCapacity(additional);
    }

    /// Ensures the map's total capacity can fit at least `new_capacity`
    /// entries under the load factor without a rehash.
    pub fn ensureTotalCapacity(self: *CharBoolHashMap, new_capacity: usize) Allocator.Error!void {
        if (new_capacity <= self.inner.len()) return;
        return self.inner.ensureCapacity(new_capacity - self.inner.len());
    }

    // ---- Iteration ----

    pub fn forEach(self: *const CharBoolHashMap, f: *const fn (u21, bool) void) void {
        self.inner.forEach(f);
    }

    pub fn forEachKey(self: *const CharBoolHashMap, f: *const fn (u21) void) void {
        self.inner.forEachKey(f);
    }

    pub fn forEachValue(self: *const CharBoolHashMap, f: *const fn (bool) void) void {
        self.inner.forEachValue(f);
    }

    // ---- Functional Operations ----

    pub fn select(self: *const CharBoolHashMap, predicate: *const fn (u21, bool) bool) CharBoolHashMap {
        var result = init(self.config.base);
        for (0..self.inner.capacity) |i| {
            if (self.inner.entries[i].occupied) {
                if (predicate(self.inner.entries[i].key, self.inner.entries[i].value))
                    _ = result.put(self.inner.entries[i].key, self.inner.entries[i].value);
            }
        }
        return result;
    }

    pub fn reject(self: *const CharBoolHashMap, predicate: *const fn (u21, bool) bool) CharBoolHashMap {
        var result = init(self.config.base);
        for (0..self.inner.capacity) |i| {
            if (self.inner.entries[i].occupied) {
                if (!predicate(self.inner.entries[i].key, self.inner.entries[i].value))
                    _ = result.put(self.inner.entries[i].key, self.inner.entries[i].value);
            }
        }
        return result;
    }

    pub fn detect(self: *const CharBoolHashMap, predicate: *const fn (u21, bool) bool) ?struct { key: u21, value: bool } {
        for (0..self.inner.capacity) |i| {
            if (self.inner.entries[i].occupied) {
                if (predicate(self.inner.entries[i].key, self.inner.entries[i].value))
                    return .{ .key = self.inner.entries[i].key, .value = self.inner.entries[i].value };
            }
        }
        return null;
    }

    pub fn anySatisfy(self: *const CharBoolHashMap, predicate: *const fn (u21, bool) bool) bool {
        for (0..self.inner.capacity) |i| {
            if (self.inner.entries[i].occupied and predicate(self.inner.entries[i].key, self.inner.entries[i].value)) return true;
        }
        return false;
    }

    pub fn allSatisfy(self: *const CharBoolHashMap, predicate: *const fn (u21, bool) bool) bool {
        for (0..self.inner.capacity) |i| {
            if (self.inner.entries[i].occupied and !predicate(self.inner.entries[i].key, self.inner.entries[i].value)) return false;
        }
        return true;
    }

    pub fn noneSatisfy(self: *const CharBoolHashMap, predicate: *const fn (u21, bool) bool) bool {
        for (0..self.inner.capacity) |i| {
            if (self.inner.entries[i].occupied and predicate(self.inner.entries[i].key, self.inner.entries[i].value)) return false;
        }
        return true;
    }

    pub fn count(self: *const CharBoolHashMap, predicate: *const fn (u21, bool) bool) usize {
        var c: usize = 0;
        for (0..self.inner.capacity) |i| {
            if (self.inner.entries[i].occupied and predicate(self.inner.entries[i].key, self.inner.entries[i].value)) c += 1;
        }
        return c;
    }

    pub fn injectInto(self: *const CharBoolHashMap, initial: bool, f: *const fn (bool, u21, bool) bool) bool {
        var acc = initial;
        for (0..self.inner.capacity) |i| {
            if (self.inner.entries[i].occupied) acc = f(acc, self.inner.entries[i].key, self.inner.entries[i].value);
        }
        return acc;
    }

    // ---- Key/Value Collection ----

    pub fn keysToSlice(self: *const CharBoolHashMap, allocator: Allocator) []u21 {
        return self.inner.keysToSlice(allocator) catch @panic("out of memory");
    }

    pub fn valuesToSlice(self: *const CharBoolHashMap, allocator: Allocator) []bool {
        return self.inner.valuesToSlice(allocator) catch @panic("out of memory");
    }

    // ---- Conversion ----

    pub fn toImmutable(self: *const CharBoolHashMap) ImmutableCharBoolHashMap {
        return ImmutableCharBoolHashMap.fromMutable(self.config.base, self);
    }

    // ---- Fluent API ----

    pub fn withKeyValue(self: *CharBoolHashMap, key: u21, value: bool) *CharBoolHashMap {
        _ = self.put(key, value);
        return self;
    }

    pub fn withoutKey(self: *CharBoolHashMap, key: u21) *CharBoolHashMap {
        _ = self.remove(key);
        return self;
    }

    pub fn withoutAllKeys(self: *CharBoolHashMap, keys: []const u21) *CharBoolHashMap {
        for (keys) |key| _ = self.remove(key);
        return self;
    }

    // ---- Mutation Helpers ----

    pub fn updateValue(self: *CharBoolHashMap, key: u21, initial: bool, f: *const fn (bool) bool) bool {
        const current = self.get(key) orelse initial;
        const new_value = f(current);
        _ = self.put(key, new_value);
        return new_value;
    }

    // ---- Formatting ----

    pub fn format(self: *const CharBoolHashMap, comptime _: []const u8, _: std.fmt.FormatOptions, writer: anytype) !void {
        try writer.writeAll("{");
        var first = true;
        for (0..self.inner.capacity) |i| {
            if (self.inner.entries[i].occupied) {
                if (!first) try writer.writeAll(", ");
                try std.fmt.formatType(self.inner.entries[i].key, "", .{}, writer, 0);
                try writer.writeAll("=");
                try std.fmt.formatType(self.inner.entries[i].value, "", .{}, writer, 0);
                first = false;
            }
        }
        try writer.writeAll("}");
    }

    // ---- Equality ----

    pub fn eql(self: *const CharBoolHashMap, other: *const CharBoolHashMap) bool {
        if (self.len() != other.len()) return false;
        for (0..self.inner.capacity) |i| {
            if (self.inner.entries[i].occupied) {
                const other_val = other.get(self.inner.entries[i].key) orelse return false;
                if (!(self.inner.entries[i].value == other_val)) return false;
            }
        }
        return true;
    }
};

// ---- Tests ----

test "CharBoolHashMap: put and get" {
    var m = CharBoolHashMap.init(std.testing.allocator);
    defer m.deinit();
    _ = m.put('a', true);
    _ = m.put('b', false);
    _ = m.put('c', true);
    try std.testing.expectEqual(@as(?bool, true), m.get('a'));
    try std.testing.expectEqual(@as(?bool, null), m.get('z'));
    try std.testing.expectEqual(@as(usize, 3), m.len());
}

test "CharBoolHashMap: put overwrite" {
    var m = CharBoolHashMap.init(std.testing.allocator);
    defer m.deinit();
    _ = m.put('a', true);
    const old = m.put('a', false);
    try std.testing.expectEqual(@as(?bool, true), old);
    try std.testing.expectEqual(@as(?bool, false), m.get('a'));
}

test "CharBoolHashMap: remove" {
    var m = CharBoolHashMap.init(std.testing.allocator);
    defer m.deinit();
    _ = m.put('a', true);
    _ = m.put('b', false);
    const removed = m.remove('a');
    try std.testing.expectEqual(@as(?bool, true), removed);
    try std.testing.expectEqual(@as(usize, 1), m.len());
    try std.testing.expect(!m.containsKey('a'));
}

test "CharBoolHashMap: containsKey and containsValue" {
    var m = CharBoolHashMap.init(std.testing.allocator);
    defer m.deinit();
    _ = m.put('a', true);
    try std.testing.expect(m.containsKey('a'));
    try std.testing.expect(!m.containsKey('z'));
    try std.testing.expect(m.containsValue(true));
    try std.testing.expect(!m.containsValue(false));
}

test "CharBoolHashMap: getOrDefault" {
    var m = CharBoolHashMap.init(std.testing.allocator);
    defer m.deinit();
    _ = m.put('a', true);
    try std.testing.expectEqual(true, m.getOrDefault('a', true));
    try std.testing.expectEqual(true, m.getOrDefault('z', true));
}

test "CharBoolHashMap: clear" {
    var m = CharBoolHashMap.init(std.testing.allocator);
    defer m.deinit();
    _ = m.put('a', true);
    m.clear();
    try std.testing.expect(m.isEmpty());
}

test "CharBoolHashMap: select" {
    var m = CharBoolHashMap.init(std.testing.allocator);
    defer m.deinit();
    _ = m.put('a', true);
    _ = m.put('b', false);
    var sel = m.select(struct {
        fn f(_: u21, v: bool) bool {
            return v == true;
        }
    }.f);
    defer sel.deinit();
    try std.testing.expect(sel.len() >= 1);
}

test "CharBoolHashMap: keysToSlice and valuesToSlice" {
    var m = CharBoolHashMap.init(std.testing.allocator);
    defer m.deinit();
    _ = m.put('a', true);
    _ = m.put('b', false);
    const keys = m.keysToSlice(std.testing.allocator);
    defer std.testing.allocator.free(keys);
    try std.testing.expectEqual(@as(usize, 2), keys.len);
    const vals = m.valuesToSlice(std.testing.allocator);
    defer std.testing.allocator.free(vals);
    try std.testing.expectEqual(@as(usize, 2), vals.len);
}

test "CharBoolHashMap: toImmutable" {
    var m = CharBoolHashMap.init(std.testing.allocator);
    defer m.deinit();
    _ = m.put('a', true);
    _ = m.put('b', false);
    var im = m.toImmutable();
    defer im.deinit();
    try std.testing.expectEqual(@as(usize, 2), im.len());
    _ = m.put('c', true);
    try std.testing.expectEqual(@as(usize, 2), im.len());
}

test "CharBoolHashMap: fluent withKeyValue/withoutKey" {
    var m = CharBoolHashMap.init(std.testing.allocator);
    defer m.deinit();
    _ = m.withKeyValue('a', true).withKeyValue('b', false);
    try std.testing.expectEqual(@as(usize, 2), m.len());
    _ = m.withoutKey('a');
    try std.testing.expectEqual(@as(usize, 1), m.len());
}

test "CharBoolHashMap: eql" {
    var m1 = CharBoolHashMap.init(std.testing.allocator);
    defer m1.deinit();
    _ = m1.put('a', true);
    _ = m1.put('b', false);
    var m2 = CharBoolHashMap.init(std.testing.allocator);
    defer m2.deinit();
    _ = m2.put('b', false);
    _ = m2.put('a', true);
    try std.testing.expect(m1.eql(&m2));
}

test "CharBoolHashMap: resize" {
    var m = CharBoolHashMap.init(std.testing.allocator);
    defer m.deinit();
    var i: usize = 0;
    while (i < 50) : (i += 1) {
        _ = m.put(@as(u21, @intCast(i % 26)) + 'a', i % 3 == 0);
    }
    try std.testing.expect(m.len() > 0);
}

test "CharBoolHashMap: entry orInsert" {
    var m = CharBoolHashMap.init(std.testing.allocator);
    defer m.deinit();
    // Key absent — inserts default
    const v1 = m.getEntry('a').orInsert(true);
    try std.testing.expectEqual(true, v1);
    // Key present — returns existing
    _ = m.put('a', false);
    const v2 = m.getEntry('a').orInsert(true);
    try std.testing.expectEqual(false, v2);
}

test "CharBoolHashMap: entry andModify orInsert" {
    var m = CharBoolHashMap.init(std.testing.allocator);
    defer m.deinit();
    // Key absent: andModify is no-op, orInsert inserts
    _ = m.getEntry('a').andModify(struct {
        fn f(_: *bool) void {}
    }.f).orInsert(true);
    try std.testing.expectEqual(@as(?bool, true), m.get('a'));
}

test "CharBoolHashMap: ensureUnusedCapacity reserves and subsequent put does not resize" {
    var m = CharBoolHashMap.init(std.testing.allocator);
    defer m.deinit();
    try m.ensureUnusedCapacity(500);
    const reserved = m.inner.capacity;
    try std.testing.expect(reserved >= 500);
    _ = m.put('a', true);
    _ = m.put('b', false);
    try std.testing.expectEqual(reserved, m.inner.capacity);
}

test "CharBoolHashMap: ensureTotalCapacity is idempotent when capacity already sufficient" {
    var m = CharBoolHashMap.init(std.testing.allocator);
    defer m.deinit();
    try m.ensureTotalCapacity(500);
    const reserved = m.inner.capacity;
    try m.ensureTotalCapacity(10);
    try std.testing.expectEqual(reserved, m.inner.capacity);
}

test "CharBoolHashMap: ensureUnusedCapacity propagates allocator error" {
    // fail_index = 1: HashMap.init allocates the backing hash table (1st alloc),
    // then ensureUnusedCapacity triggers a grow that fails (2nd alloc).
    var failing = std.testing.FailingAllocator.init(std.testing.allocator, .{ .fail_index = 1 });
    var m = CharBoolHashMap.init(failing.allocator());
    defer m.deinit();
    try std.testing.expectError(error.OutOfMemory, m.ensureUnusedCapacity(10_000));
}
