// Code generated by mapdb-codegen. DO NOT EDIT.

const std = @import("std");
const Allocator = std.mem.Allocator;

/// Primitive min-heap priority queue of `i32` values, backed by an
/// `ArrayListUnmanaged`. O(log n) push/pop, O(1) peek.
pub const I32PriorityQueue = struct {
    items: std.ArrayListUnmanaged(i32) = .empty,
    allocator: Allocator,

    pub fn init(allocator: Allocator) I32PriorityQueue {
        return .{ .allocator = allocator };
    }

    pub fn deinit(self: *I32PriorityQueue) void {
        self.items.deinit(self.allocator);
    }

    pub fn of(allocator: Allocator, values: []const i32) I32PriorityQueue {
        var q = init(allocator);
        q.items.appendSlice(q.allocator, values) catch @panic("out of memory");
        if (q.items.items.len > 1) {
            var i: usize = q.items.items.len / 2;
            while (i > 0) {
                i -= 1;
                q.siftDown(i);
            }
        }
        return q;
    }

    /// Pushes a value onto the heap. O(log n).
    pub fn push(self: *I32PriorityQueue, value: i32) void {
        self.items.append(self.allocator, value) catch @panic("out of memory");
        self.siftUp(self.items.items.len - 1);
    }

    /// Removes and returns the smallest element, or null if empty. O(log n).
    pub fn pop(self: *I32PriorityQueue) ?i32 {
        if (self.items.items.len == 0) return null;
        const top = self.items.items[0];
        const last = self.items.pop().?;
        if (self.items.items.len > 0) {
            self.items.items[0] = last;
            self.siftDown(0);
        }
        return top;
    }

    /// Returns the smallest element without removing it, or null if empty.
    pub fn peek(self: *const I32PriorityQueue) ?i32 {
        if (self.items.items.len == 0) return null;
        return self.items.items[0];
    }

    pub fn len(self: *const I32PriorityQueue) usize {
        return self.items.items.len;
    }
    pub fn isEmpty(self: *const I32PriorityQueue) bool {
        return self.items.items.len == 0;
    }
    pub fn clear(self: *I32PriorityQueue) void {
        self.items.clearRetainingCapacity();
    }

    pub fn ensureUnusedCapacity(self: *I32PriorityQueue, additional: usize) Allocator.Error!void {
        try self.items.ensureUnusedCapacity(self.allocator, additional);
    }

    pub fn contains(self: *const I32PriorityQueue, value: i32) bool {
        for (self.items.items) |v| {
            if (v == value) return true;
        }
        return false;
    }

    /// Returns a slice view of the internal heap array (NOT sorted).
    pub fn slice(self: *const I32PriorityQueue) []const i32 {
        return self.items.items;
    }

    /// Drains the heap into a caller-owned slice in ascending order.
    pub fn drainSorted(self: *I32PriorityQueue, allocator: Allocator) []i32 {
        const out = allocator.alloc(i32, self.items.items.len) catch @panic("out of memory");
        var i: usize = 0;
        while (self.pop()) |v| : (i += 1) {
            out[i] = v;
        }
        return out;
    }

    fn siftUp(self: *I32PriorityQueue, start: usize) void {
        var i = start;
        while (i > 0) {
            const parent = (i - 1) / 2;
            if (self.items.items[i] < self.items.items[parent]) {
                const tmp = self.items.items[i];
                self.items.items[i] = self.items.items[parent];
                self.items.items[parent] = tmp;
                i = parent;
            } else break;
        }
    }

    fn siftDown(self: *I32PriorityQueue, start: usize) void {
        var i = start;
        const n = self.items.items.len;
        while (true) {
            const left = 2 * i + 1;
            if (left >= n) break;
            const right = left + 1;
            var best = left;
            if (right < n and self.items.items[right] < self.items.items[left]) {
                best = right;
            }
            if (self.items.items[best] < self.items.items[i]) {
                const tmp = self.items.items[best];
                self.items.items[best] = self.items.items[i];
                self.items.items[i] = tmp;
                i = best;
            } else break;
        }
    }
};

test "I32PriorityQueue: push peek pop min" {
    var q = I32PriorityQueue.init(std.testing.allocator);
    defer q.deinit();
    q.push(3);
    q.push(1);
    q.push(2);
    try std.testing.expectEqual(@as(usize, 3), q.len());

    try std.testing.expectEqual(@as(?i32, 1), q.peek());
    const a = q.pop().?;
    const b = q.pop().?;
    const c = q.pop().?;
    try std.testing.expect(!(b < a));
    try std.testing.expect(!(c < b));

    try std.testing.expectEqual(@as(?i32, null), q.pop());
}

test "I32PriorityQueue: of heapify" {
    var q = I32PriorityQueue.of(std.testing.allocator, &[_]i32{ 3, 1, 2 });
    defer q.deinit();
    try std.testing.expectEqual(@as(usize, 3), q.len());
    try std.testing.expectEqual(@as(?i32, 1), q.peek());
}

test "I32PriorityQueue: empty" {
    var q = I32PriorityQueue.init(std.testing.allocator);
    defer q.deinit();
    try std.testing.expect(q.isEmpty());
    try std.testing.expectEqual(@as(?i32, null), q.peek());
    try std.testing.expectEqual(@as(?i32, null), q.pop());
}

test "I32PriorityQueue: contains clear" {
    var q = I32PriorityQueue.init(std.testing.allocator);
    defer q.deinit();
    q.push(1);
    try std.testing.expect(q.contains(1));
    q.clear();
    try std.testing.expect(q.isEmpty());
}

test "I32PriorityQueue: drainSorted" {
    var q = I32PriorityQueue.of(std.testing.allocator, &[_]i32{ 3, 1, 2 });
    defer q.deinit();
    const sorted = q.drainSorted(std.testing.allocator);
    defer std.testing.allocator.free(sorted);
    try std.testing.expectEqual(@as(usize, 3), sorted.len);

    var i: usize = 1;
    while (i < sorted.len) : (i += 1) {
        try std.testing.expect(!(sorted[i] < sorted[i - 1]));
    }
}
