// Code generated by mapdb-codegen. DO NOT EDIT.

const std = @import("std");
const Allocator = std.mem.Allocator;
const I16PriorityQueue = @import("../priority_queue/i16_priority_queue.zig").I16PriorityQueue;

/// Immutable min-heap priority queue of `i16` values, backed by an owned
/// heap-ordered slice. All "mutating" operations return new immutable queues.
pub const ImmutableI16PriorityQueue = struct {
    items: []const i16,
    allocator: Allocator,

    /// Heapifies `values` (copy) and wraps the result. O(n).
    pub fn of(allocator: Allocator, values: []const i16) ImmutableI16PriorityQueue {
        var tmp = I16PriorityQueue.of(allocator, values);
        defer tmp.deinit();
        const owned = allocator.dupe(i16, tmp.slice()) catch @panic("out of memory");
        return .{ .items = owned, .allocator = allocator };
    }

    pub fn fromMutable(allocator: Allocator, mutable: *const I16PriorityQueue) ImmutableI16PriorityQueue {
        const owned = allocator.dupe(i16, mutable.slice()) catch @panic("out of memory");
        return .{ .items = owned, .allocator = allocator };
    }

    pub fn deinit(self: *ImmutableI16PriorityQueue) void {
        self.allocator.free(self.items);
    }

    /// Returns the smallest element without removing it, or null if empty.
    pub fn peek(self: *const ImmutableI16PriorityQueue) ?i16 {
        if (self.items.len == 0) return null;
        return self.items[0];
    }

    pub fn len(self: *const ImmutableI16PriorityQueue) usize {
        return self.items.len;
    }
    pub fn isEmpty(self: *const ImmutableI16PriorityQueue) bool {
        return self.items.len == 0;
    }

    pub fn contains(self: *const ImmutableI16PriorityQueue, value: i16) bool {
        for (self.items) |item| {
            if (item == value) return true;
        }
        return false;
    }

    /// Returns a slice view of the internal heap array (NOT sorted).
    pub fn slice(self: *const ImmutableI16PriorityQueue) []const i16 {
        return self.items;
    }

    /// Returns a new immutable queue with `value` inserted. O(n) due to copy.
    pub fn push(self: *const ImmutableI16PriorityQueue, value: i16) ImmutableI16PriorityQueue {
        var m = self.toMutable();
        defer m.deinit();
        m.push(value);
        const owned = self.allocator.dupe(i16, m.slice()) catch @panic("out of memory");
        return .{ .items = owned, .allocator = self.allocator };
    }

    /// Returns a new queue without the smallest element, and the removed value.
    pub fn pop(self: *const ImmutableI16PriorityQueue) ?struct { queue: ImmutableI16PriorityQueue, value: i16 } {
        if (self.items.len == 0) return null;
        var m = self.toMutable();
        defer m.deinit();
        const top = m.pop().?;
        const owned = self.allocator.dupe(i16, m.slice()) catch @panic("out of memory");
        return .{
            .queue = .{ .items = owned, .allocator = self.allocator },
            .value = top,
        };
    }

    pub fn toMutable(self: *const ImmutableI16PriorityQueue) I16PriorityQueue {
        return I16PriorityQueue.of(self.allocator, self.items);
    }

    pub fn eql(self: *const ImmutableI16PriorityQueue, other: *const ImmutableI16PriorityQueue) bool {
        if (self.items.len != other.items.len) return false;
        for (self.items, other.items) |a, b| {
            if (!(a == b)) return false;
        }
        return true;
    }
};

test "ImmutableI16PriorityQueue: of and peek" {
    var q = ImmutableI16PriorityQueue.of(std.testing.allocator, &[_]i16{ 3, 1, 2 });
    defer q.deinit();
    try std.testing.expectEqual(@as(usize, 3), q.len());
    try std.testing.expect(q.peek() != null);
}

test "ImmutableI16PriorityQueue: persistent push" {
    var q1 = ImmutableI16PriorityQueue.of(std.testing.allocator, &[_]i16{3});
    defer q1.deinit();
    var q2 = q1.push(1);
    defer q2.deinit();
    try std.testing.expectEqual(@as(usize, 1), q1.len());
    try std.testing.expectEqual(@as(usize, 2), q2.len());
    try std.testing.expect(q2.peek() != null);
}

test "ImmutableI16PriorityQueue: pop returns smallest and new queue" {
    var q = ImmutableI16PriorityQueue.of(std.testing.allocator, &[_]i16{ 3, 1, 2 });
    defer q.deinit();
    const r = q.pop().?;
    var q2 = r.queue;
    defer q2.deinit();
    _ = r.value;
    try std.testing.expectEqual(@as(usize, 2), q2.len());
    // Original untouched
    try std.testing.expectEqual(@as(usize, 3), q.len());
}

test "ImmutableI16PriorityQueue: fromMutable independence" {
    var m = I16PriorityQueue.init(std.testing.allocator);
    defer m.deinit();
    m.push(1);
    m.push(2);
    var im = ImmutableI16PriorityQueue.fromMutable(std.testing.allocator, &m);
    defer im.deinit();
    var m2 = im.toMutable();
    defer m2.deinit();
    m2.push(3);
    try std.testing.expectEqual(@as(usize, 2), im.len());
    try std.testing.expectEqual(@as(usize, 3), m2.len());
}
