// Code generated by mapdb-codegen. DO NOT EDIT.

const std = @import("std");
const Allocator = std.mem.Allocator;
const OpenHashMap = @import("../hash_table.zig").OpenHashMap;
const I8BoolHashMap = @import("../hashmap/i8_bool_hash_map.zig").I8BoolHashMap;

/// Immutable hash map from `i8` keys to `bool` values.
///
/// Backed by a snapshot of the internal hash map. All operations are read-only.
pub const ImmutableI8BoolHashMap = struct {
    inner: OpenHashMap(i8, bool),
    allocator: Allocator,

    pub fn fromMutable(allocator: Allocator, mutable: *const I8BoolHashMap) ImmutableI8BoolHashMap {
        var inner = OpenHashMap(i8, bool).init(allocator, allocator, allocator) catch @panic("out of memory");
        for (0..mutable.inner.capacity) |i| {
            if (mutable.inner.entries[i].occupied) {
                _ = inner.put(mutable.inner.entries[i].key, mutable.inner.entries[i].value) catch @panic("out of memory");
            }
        }
        return .{ .inner = inner, .allocator = allocator };
    }

    pub fn deinit(self: *ImmutableI8BoolHashMap) void {
        self.inner.deinit();
    }

    pub fn get(self: *const ImmutableI8BoolHashMap, key: i8) ?bool {
        return self.inner.get(key);
    }

    pub fn getOrDefault(self: *const ImmutableI8BoolHashMap, key: i8, default_value: bool) bool {
        return self.get(key) orelse default_value;
    }

    pub fn containsKey(self: *const ImmutableI8BoolHashMap, key: i8) bool {
        return self.inner.containsKey(key);
    }

    pub fn containsValue(self: *const ImmutableI8BoolHashMap, value: bool) bool {
        return self.inner.containsValue(value);
    }

    pub fn len(self: *const ImmutableI8BoolHashMap) usize {
        return self.inner.len();
    }

    pub fn isEmpty(self: *const ImmutableI8BoolHashMap) bool {
        return self.inner.isEmpty();
    }

    pub fn toMutable(self: *const ImmutableI8BoolHashMap) I8BoolHashMap {
        var mutable = I8BoolHashMap.init(self.allocator);
        for (0..self.inner.capacity) |i| {
            if (self.inner.entries[i].occupied) {
                _ = mutable.put(self.inner.entries[i].key, self.inner.entries[i].value);
            }
        }
        return mutable;
    }

    pub fn eql(self: *const ImmutableI8BoolHashMap, other: *const ImmutableI8BoolHashMap) bool {
        if (self.len() != other.len()) return false;
        for (0..self.inner.capacity) |i| {
            if (self.inner.entries[i].occupied) {
                const other_val = other.get(self.inner.entries[i].key) orelse return false;
                if (!(self.inner.entries[i].value == other_val)) return false;
            }
        }
        return true;
    }
};

test "ImmutableI8BoolHashMap: fromMutable and get" {
    var mm = I8BoolHashMap.init(std.testing.allocator);
    defer mm.deinit();
    _ = mm.put(1, true);
    _ = mm.put(2, false);
    var im = ImmutableI8BoolHashMap.fromMutable(std.testing.allocator, &mm);
    defer im.deinit();
    try std.testing.expectEqual(@as(?bool, true), im.get(1));
    try std.testing.expectEqual(@as(usize, 2), im.len());
}

test "ImmutableI8BoolHashMap: toMutable independence" {
    var mm = I8BoolHashMap.init(std.testing.allocator);
    _ = mm.put(1, true);
    var im = ImmutableI8BoolHashMap.fromMutable(std.testing.allocator, &mm);
    mm.deinit();
    defer im.deinit();
    var mm2 = im.toMutable();
    defer mm2.deinit();
    _ = mm2.put(2, false);
    try std.testing.expectEqual(@as(usize, 1), im.len());
    try std.testing.expectEqual(@as(usize, 2), mm2.len());
}
