// Code generated by mapdb-codegen. DO NOT EDIT.

const std = @import("std");
const Allocator = std.mem.Allocator;
const OpenHashMap = @import("../hash_table.zig").OpenHashMap;
const I16I64HashMap = @import("../hashmap/i16_i64_hash_map.zig").I16I64HashMap;

/// Immutable hash map from `i16` keys to `i64` values.
///
/// Backed by a snapshot of the internal hash map. All operations are read-only.
pub const ImmutableI16I64HashMap = struct {
    inner: OpenHashMap(i16, i64),
    allocator: Allocator,

    pub fn fromMutable(allocator: Allocator, mutable: *const I16I64HashMap) ImmutableI16I64HashMap {
        var inner = OpenHashMap(i16, i64).init(allocator, allocator, allocator) catch @panic("out of memory");
        for (0..mutable.inner.capacity) |i| {
            if (mutable.inner.entries[i].occupied) {
                _ = inner.put(mutable.inner.entries[i].key, mutable.inner.entries[i].value) catch @panic("out of memory");
            }
        }
        return .{ .inner = inner, .allocator = allocator };
    }

    pub fn deinit(self: *ImmutableI16I64HashMap) void {
        self.inner.deinit();
    }

    pub fn get(self: *const ImmutableI16I64HashMap, key: i16) ?i64 {
        return self.inner.get(key);
    }

    pub fn getOrDefault(self: *const ImmutableI16I64HashMap, key: i16, default_value: i64) i64 {
        return self.get(key) orelse default_value;
    }

    pub fn containsKey(self: *const ImmutableI16I64HashMap, key: i16) bool {
        return self.inner.containsKey(key);
    }

    pub fn containsValue(self: *const ImmutableI16I64HashMap, value: i64) bool {
        return self.inner.containsValue(value);
    }

    pub fn len(self: *const ImmutableI16I64HashMap) usize {
        return self.inner.len();
    }

    pub fn isEmpty(self: *const ImmutableI16I64HashMap) bool {
        return self.inner.isEmpty();
    }

    pub fn toMutable(self: *const ImmutableI16I64HashMap) I16I64HashMap {
        var mutable = I16I64HashMap.init(self.allocator);
        for (0..self.inner.capacity) |i| {
            if (self.inner.entries[i].occupied) {
                _ = mutable.put(self.inner.entries[i].key, self.inner.entries[i].value);
            }
        }
        return mutable;
    }

    pub fn eql(self: *const ImmutableI16I64HashMap, other: *const ImmutableI16I64HashMap) bool {
        if (self.len() != other.len()) return false;
        for (0..self.inner.capacity) |i| {
            if (self.inner.entries[i].occupied) {
                const other_val = other.get(self.inner.entries[i].key) orelse return false;
                if (!(self.inner.entries[i].value == other_val)) return false;
            }
        }
        return true;
    }
};

test "ImmutableI16I64HashMap: fromMutable and get" {
    var mm = I16I64HashMap.init(std.testing.allocator);
    defer mm.deinit();
    _ = mm.put(1, 1);
    _ = mm.put(2, 2);
    var im = ImmutableI16I64HashMap.fromMutable(std.testing.allocator, &mm);
    defer im.deinit();
    try std.testing.expectEqual(@as(?i64, 1), im.get(1));
    try std.testing.expectEqual(@as(usize, 2), im.len());
}

test "ImmutableI16I64HashMap: toMutable independence" {
    var mm = I16I64HashMap.init(std.testing.allocator);
    _ = mm.put(1, 1);
    var im = ImmutableI16I64HashMap.fromMutable(std.testing.allocator, &mm);
    mm.deinit();
    defer im.deinit();
    var mm2 = im.toMutable();
    defer mm2.deinit();
    _ = mm2.put(2, 2);
    try std.testing.expectEqual(@as(usize, 1), im.len());
    try std.testing.expectEqual(@as(usize, 2), mm2.len());
}
