// Code generated by mapdb-codegen. DO NOT EDIT.

const std = @import("std");
const Allocator = std.mem.Allocator;
const F32ArrayDeque = @import("../deque/f32_array_deque.zig").F32ArrayDeque;

/// Immutable deque of `f32` values, backed by an owned allocated slice.
/// All "mutating" operations return new immutable deques.
pub const ImmutableF32ArrayDeque = struct {
    items: []const f32,
    allocator: Allocator,

    pub fn of(allocator: Allocator, values: []const f32) ImmutableF32ArrayDeque {
        const owned = allocator.dupe(f32, values) catch @panic("out of memory");
        return .{ .items = owned, .allocator = allocator };
    }

    pub fn fromMutable(allocator: Allocator, mutable: *const F32ArrayDeque) ImmutableF32ArrayDeque {
        return of(allocator, mutable.items.items);
    }

    pub fn deinit(self: *ImmutableF32ArrayDeque) void {
        self.allocator.free(self.items);
    }

    pub fn peekFirst(self: *const ImmutableF32ArrayDeque) ?f32 {
        if (self.items.len == 0) return null;
        return self.items[0];
    }

    pub fn peekLast(self: *const ImmutableF32ArrayDeque) ?f32 {
        if (self.items.len == 0) return null;
        return self.items[self.items.len - 1];
    }

    pub fn len(self: *const ImmutableF32ArrayDeque) usize {
        return self.items.len;
    }
    pub fn isEmpty(self: *const ImmutableF32ArrayDeque) bool {
        return self.items.len == 0;
    }

    pub fn contains(self: *const ImmutableF32ArrayDeque, value: f32) bool {
        for (self.items) |item| {
            if (@as(u32, @bitCast(item)) == @as(u32, @bitCast(value))) return true;
        }
        return false;
    }

    pub fn toSlice(self: *const ImmutableF32ArrayDeque) []const f32 {
        return self.items;
    }

    /// Returns a new immutable deque with `value` prepended at the front.
    pub fn withFirst(self: *const ImmutableF32ArrayDeque, value: f32) ImmutableF32ArrayDeque {
        const new_items = self.allocator.alloc(f32, self.items.len + 1) catch @panic("out of memory");
        new_items[0] = value;
        @memcpy(new_items[1..], self.items);
        return .{ .items = new_items, .allocator = self.allocator };
    }

    /// Returns a new immutable deque with `value` appended at the back.
    pub fn withLast(self: *const ImmutableF32ArrayDeque, value: f32) ImmutableF32ArrayDeque {
        const new_items = self.allocator.alloc(f32, self.items.len + 1) catch @panic("out of memory");
        @memcpy(new_items[0..self.items.len], self.items);
        new_items[self.items.len] = value;
        return .{ .items = new_items, .allocator = self.allocator };
    }

    /// Returns a new deque without the front element, and the removed value.
    pub fn withoutFirst(self: *const ImmutableF32ArrayDeque) ?struct { deque: ImmutableF32ArrayDeque, value: f32 } {
        if (self.items.len == 0) return null;
        const first = self.items[0];
        const new_items = self.allocator.dupe(f32, self.items[1..]) catch @panic("out of memory");
        return .{
            .deque = .{ .items = new_items, .allocator = self.allocator },
            .value = first,
        };
    }

    /// Returns a new deque without the back element, and the removed value.
    pub fn withoutLast(self: *const ImmutableF32ArrayDeque) ?struct { deque: ImmutableF32ArrayDeque, value: f32 } {
        if (self.items.len == 0) return null;
        const last = self.items[self.items.len - 1];
        const new_items = self.allocator.dupe(f32, self.items[0 .. self.items.len - 1]) catch @panic("out of memory");
        return .{
            .deque = .{ .items = new_items, .allocator = self.allocator },
            .value = last,
        };
    }

    pub fn forEach(self: *const ImmutableF32ArrayDeque, f: *const fn (f32) void) void {
        for (self.items) |value| f(value);
    }

    pub fn toMutable(self: *const ImmutableF32ArrayDeque) F32ArrayDeque {
        return F32ArrayDeque.of(self.allocator, self.items);
    }

    pub fn eql(self: *const ImmutableF32ArrayDeque, other: *const ImmutableF32ArrayDeque) bool {
        if (self.items.len != other.items.len) return false;
        for (self.items, other.items) |a, b| {
            if (!(@as(u32, @bitCast(a)) == @as(u32, @bitCast(b)))) return false;
        }
        return true;
    }
};

test "ImmutableF32ArrayDeque: of and peek" {
    var d = ImmutableF32ArrayDeque.of(std.testing.allocator, &[_]f32{ 1.0, 2.0, 3.0 });
    defer d.deinit();
    try std.testing.expectEqual(@as(usize, 3), d.len());
    try std.testing.expectEqual(@as(?f32, 1.0), d.peekFirst());
    try std.testing.expectEqual(@as(?f32, 3.0), d.peekLast());
}

test "ImmutableF32ArrayDeque: persistent withFirst/withLast" {
    var d1 = ImmutableF32ArrayDeque.of(std.testing.allocator, &[_]f32{2.0});
    defer d1.deinit();
    var d2 = d1.withFirst(1.0);
    defer d2.deinit();
    var d3 = d2.withLast(3.0);
    defer d3.deinit();
    try std.testing.expectEqual(@as(usize, 1), d1.len());
    try std.testing.expectEqual(@as(usize, 3), d3.len());
    try std.testing.expectEqual(@as(?f32, 1.0), d3.peekFirst());
    try std.testing.expectEqual(@as(?f32, 3.0), d3.peekLast());
}

test "ImmutableF32ArrayDeque: withoutFirst/withoutLast" {
    var d = ImmutableF32ArrayDeque.of(std.testing.allocator, &[_]f32{ 1.0, 2.0, 3.0 });
    defer d.deinit();
    const r1 = d.withoutFirst().?;
    var d2 = r1.deque;
    defer d2.deinit();
    try std.testing.expectEqual(1.0, r1.value);
    try std.testing.expectEqual(@as(usize, 2), d2.len());

    const r2 = d.withoutLast().?;
    var d3 = r2.deque;
    defer d3.deinit();
    try std.testing.expectEqual(3.0, r2.value);
    try std.testing.expectEqual(@as(usize, 2), d3.len());

    // Original untouched
    try std.testing.expectEqual(@as(usize, 3), d.len());
}

test "ImmutableF32ArrayDeque: fromMutable and toMutable independence" {
    var ml = F32ArrayDeque.init(std.testing.allocator);
    defer ml.deinit();
    ml.addLast(1.0);
    ml.addLast(2.0);
    var il = ImmutableF32ArrayDeque.fromMutable(std.testing.allocator, &ml);
    defer il.deinit();
    var ml2 = il.toMutable();
    defer ml2.deinit();
    ml2.addLast(3.0);
    try std.testing.expectEqual(@as(usize, 2), il.len());
    try std.testing.expectEqual(@as(usize, 3), ml2.len());
}

test "ImmutableF32ArrayDeque: eql and contains" {
    var a = ImmutableF32ArrayDeque.of(std.testing.allocator, &[_]f32{ 1.0, 2.0 });
    defer a.deinit();
    var b = ImmutableF32ArrayDeque.of(std.testing.allocator, &[_]f32{ 1.0, 2.0 });
    defer b.deinit();
    try std.testing.expect(a.eql(&b));
    try std.testing.expect(a.contains(1.0));
}
