// Code generated by mapdb-codegen. DO NOT EDIT.

const std = @import("std");
const Allocator = std.mem.Allocator;
const CharArrayStack = @import("../stack/char_array_stack.zig").CharArrayStack;

/// Immutable LIFO stack of `u21` values.
///
/// Persistent operations: `push()` and `pop()` return new immutable stacks
/// rather than modifying in place.
pub const ImmutableCharArrayStack = struct {
    items: []const u21,
    allocator: Allocator,

    pub fn of(allocator: Allocator, values: []const u21) ImmutableCharArrayStack {
        const owned = allocator.dupe(u21, values) catch @panic("out of memory");
        return .{ .items = owned, .allocator = allocator };
    }

    pub fn fromMutable(allocator: Allocator, mutable: *const CharArrayStack) ImmutableCharArrayStack {
        return of(allocator, mutable.items.items);
    }

    pub fn deinit(self: *ImmutableCharArrayStack) void {
        self.allocator.free(self.items);
    }

    pub fn peek(self: *const ImmutableCharArrayStack) ?u21 {
        if (self.items.len == 0) return null;
        return self.items[self.items.len - 1];
    }

    pub fn len(self: *const ImmutableCharArrayStack) usize {
        return self.items.len;
    }

    pub fn isEmpty(self: *const ImmutableCharArrayStack) bool {
        return self.items.len == 0;
    }

    pub fn contains(self: *const ImmutableCharArrayStack, value: u21) bool {
        for (self.items) |item| {
            if (item == value) return true;
        }
        return false;
    }

    pub fn toSlice(self: *const ImmutableCharArrayStack) []const u21 {
        return self.items;
    }

    /// Returns a new immutable stack with the value pushed on top.
    pub fn push(self: *const ImmutableCharArrayStack, value: u21) ImmutableCharArrayStack {
        const new_items = self.allocator.alloc(u21, self.items.len + 1) catch @panic("out of memory");
        @memcpy(new_items[0..self.items.len], self.items);
        new_items[self.items.len] = value;
        return .{ .items = new_items, .allocator = self.allocator };
    }

    /// Returns a new immutable stack without the top element, and the popped value.
    /// Returns null if empty.
    pub fn pop(self: *const ImmutableCharArrayStack) ?struct { stack: ImmutableCharArrayStack, value: u21 } {
        if (self.items.len == 0) return null;
        const top = self.items[self.items.len - 1];
        const new_items = self.allocator.dupe(u21, self.items[0 .. self.items.len - 1]) catch @panic("out of memory");
        return .{
            .stack = .{ .items = new_items, .allocator = self.allocator },
            .value = top,
        };
    }

    pub fn toMutable(self: *const ImmutableCharArrayStack) CharArrayStack {
        return CharArrayStack.of(self.allocator, self.items);
    }

    pub fn eql(self: *const ImmutableCharArrayStack, other: *const ImmutableCharArrayStack) bool {
        if (self.items.len != other.items.len) return false;
        for (self.items, other.items) |a, b| {
            if (!(a == b)) return false;
        }
        return true;
    }
};

test "ImmutableCharArrayStack: of and peek" {
    var il = ImmutableCharArrayStack.of(std.testing.allocator, &[_]u21{ 'a', 'b', 'c' });
    defer il.deinit();
    try std.testing.expectEqual(@as(usize, 3), il.len());
    try std.testing.expectEqual(@as(?u21, 'c'), il.peek());
}

test "ImmutableCharArrayStack: persistent push" {
    var s1 = ImmutableCharArrayStack.of(std.testing.allocator, &[_]u21{'a'});
    defer s1.deinit();
    var s2 = s1.push('b');
    defer s2.deinit();
    // Original unchanged
    try std.testing.expectEqual(@as(usize, 1), s1.len());
    try std.testing.expectEqual(@as(usize, 2), s2.len());
    try std.testing.expectEqual(@as(?u21, 'b'), s2.peek());
}

test "ImmutableCharArrayStack: persistent pop" {
    var s1 = ImmutableCharArrayStack.of(std.testing.allocator, &[_]u21{ 'a', 'b' });
    defer s1.deinit();
    const result = s1.pop().?;
    var s2 = result.stack;
    defer s2.deinit();
    try std.testing.expectEqual('b', result.value);
    try std.testing.expectEqual(@as(usize, 2), s1.len()); // unchanged
    try std.testing.expectEqual(@as(usize, 1), s2.len());
}

test "ImmutableCharArrayStack: toMutable independence" {
    var il = ImmutableCharArrayStack.of(std.testing.allocator, &[_]u21{'a'});
    defer il.deinit();
    var ml = il.toMutable();
    defer ml.deinit();
    ml.push('b');
    try std.testing.expectEqual(@as(usize, 1), il.len());
    try std.testing.expectEqual(@as(usize, 2), ml.len());
}
