// Code generated by mapdb-codegen. DO NOT EDIT.

const std = @import("std");
const Allocator = std.mem.Allocator;
const I16ArrayStack = @import("../stack/i16_array_stack.zig").I16ArrayStack;

/// Immutable LIFO stack of `i16` values.
///
/// Persistent operations: `push()` and `pop()` return new immutable stacks
/// rather than modifying in place.
pub const ImmutableI16ArrayStack = struct {
    items: []const i16,
    allocator: Allocator,

    pub fn of(allocator: Allocator, values: []const i16) ImmutableI16ArrayStack {
        const owned = allocator.dupe(i16, values) catch @panic("out of memory");
        return .{ .items = owned, .allocator = allocator };
    }

    pub fn fromMutable(allocator: Allocator, mutable: *const I16ArrayStack) ImmutableI16ArrayStack {
        return of(allocator, mutable.items.items);
    }

    pub fn deinit(self: *ImmutableI16ArrayStack) void {
        self.allocator.free(self.items);
    }

    pub fn peek(self: *const ImmutableI16ArrayStack) ?i16 {
        if (self.items.len == 0) return null;
        return self.items[self.items.len - 1];
    }

    pub fn len(self: *const ImmutableI16ArrayStack) usize {
        return self.items.len;
    }

    pub fn isEmpty(self: *const ImmutableI16ArrayStack) bool {
        return self.items.len == 0;
    }

    pub fn contains(self: *const ImmutableI16ArrayStack, value: i16) bool {
        for (self.items) |item| {
            if (item == value) return true;
        }
        return false;
    }

    pub fn toSlice(self: *const ImmutableI16ArrayStack) []const i16 {
        return self.items;
    }

    /// Returns a new immutable stack with the value pushed on top.
    pub fn push(self: *const ImmutableI16ArrayStack, value: i16) ImmutableI16ArrayStack {
        const new_items = self.allocator.alloc(i16, self.items.len + 1) catch @panic("out of memory");
        @memcpy(new_items[0..self.items.len], self.items);
        new_items[self.items.len] = value;
        return .{ .items = new_items, .allocator = self.allocator };
    }

    /// Returns a new immutable stack without the top element, and the popped value.
    /// Returns null if empty.
    pub fn pop(self: *const ImmutableI16ArrayStack) ?struct { stack: ImmutableI16ArrayStack, value: i16 } {
        if (self.items.len == 0) return null;
        const top = self.items[self.items.len - 1];
        const new_items = self.allocator.dupe(i16, self.items[0 .. self.items.len - 1]) catch @panic("out of memory");
        return .{
            .stack = .{ .items = new_items, .allocator = self.allocator },
            .value = top,
        };
    }

    pub fn toMutable(self: *const ImmutableI16ArrayStack) I16ArrayStack {
        return I16ArrayStack.of(self.allocator, self.items);
    }

    pub fn eql(self: *const ImmutableI16ArrayStack, other: *const ImmutableI16ArrayStack) bool {
        if (self.items.len != other.items.len) return false;
        for (self.items, other.items) |a, b| {
            if (!(a == b)) return false;
        }
        return true;
    }
};

test "ImmutableI16ArrayStack: of and peek" {
    var il = ImmutableI16ArrayStack.of(std.testing.allocator, &[_]i16{ 1, 2, 3 });
    defer il.deinit();
    try std.testing.expectEqual(@as(usize, 3), il.len());
    try std.testing.expectEqual(@as(?i16, 3), il.peek());
}

test "ImmutableI16ArrayStack: persistent push" {
    var s1 = ImmutableI16ArrayStack.of(std.testing.allocator, &[_]i16{1});
    defer s1.deinit();
    var s2 = s1.push(2);
    defer s2.deinit();
    // Original unchanged
    try std.testing.expectEqual(@as(usize, 1), s1.len());
    try std.testing.expectEqual(@as(usize, 2), s2.len());
    try std.testing.expectEqual(@as(?i16, 2), s2.peek());
}

test "ImmutableI16ArrayStack: persistent pop" {
    var s1 = ImmutableI16ArrayStack.of(std.testing.allocator, &[_]i16{ 1, 2 });
    defer s1.deinit();
    const result = s1.pop().?;
    var s2 = result.stack;
    defer s2.deinit();
    try std.testing.expectEqual(2, result.value);
    try std.testing.expectEqual(@as(usize, 2), s1.len()); // unchanged
    try std.testing.expectEqual(@as(usize, 1), s2.len());
}

test "ImmutableI16ArrayStack: toMutable independence" {
    var il = ImmutableI16ArrayStack.of(std.testing.allocator, &[_]i16{1});
    defer il.deinit();
    var ml = il.toMutable();
    defer ml.deinit();
    ml.push(2);
    try std.testing.expectEqual(@as(usize, 1), il.len());
    try std.testing.expectEqual(@as(usize, 2), ml.len());
}
