// Code generated by mapdb-codegen. DO NOT EDIT.

const std = @import("std");
const Allocator = std.mem.Allocator;
const OpenHashMap = @import("../hash_table.zig").OpenHashMap;
const F64HashBag = @import("../bag/f64_hash_bag.zig").F64HashBag;

/// Immutable bag (multiset) of `f64` values with occurrence counting.
///
/// Backed by a snapshot of the counts map. All operations are read-only.
pub const ImmutableF64HashBag = struct {
    counts: OpenHashMap(f64, usize),
    size: usize,
    allocator: Allocator,

    pub fn of(allocator: Allocator, values: []const f64) ImmutableF64HashBag {
        var mutable = F64HashBag.init(allocator);
        for (values) |val| mutable.add(val);
        const result = fromMutable(allocator, &mutable);
        mutable.deinit();
        return result;
    }

    pub fn fromMutable(allocator: Allocator, mutable: *const F64HashBag) ImmutableF64HashBag {
        var counts = OpenHashMap(f64, usize).init(allocator, allocator, allocator) catch @panic("out of memory");
        for (0..mutable.counts.capacity) |i| {
            if (mutable.counts.entries[i].occupied) {
                _ = counts.put(mutable.counts.entries[i].key, mutable.counts.entries[i].value) catch @panic("out of memory");
            }
        }
        return .{
            .counts = counts,
            .size = mutable.size,
            .allocator = allocator,
        };
    }

    pub fn deinit(self: *ImmutableF64HashBag) void {
        self.counts.deinit();
    }

    pub fn occurrencesOf(self: *const ImmutableF64HashBag, value: f64) usize {
        return self.counts.get(value) orelse 0;
    }

    pub fn contains(self: *const ImmutableF64HashBag, value: f64) bool {
        return self.occurrencesOf(value) > 0;
    }

    pub fn totalSize(self: *const ImmutableF64HashBag) usize {
        return self.size;
    }

    pub fn sizeDistinct(self: *const ImmutableF64HashBag) usize {
        return self.counts.len();
    }

    pub fn isEmpty(self: *const ImmutableF64HashBag) bool {
        return self.size == 0;
    }

    pub fn len(self: *const ImmutableF64HashBag) usize {
        return self.size;
    }

    pub fn toSlice(self: *const ImmutableF64HashBag) []const f64 {
        _ = self;
        // Not directly applicable for bags; use toMutable().
        return &[_]f64{};
    }

    pub fn toMutable(self: *const ImmutableF64HashBag) F64HashBag {
        var mutable = F64HashBag.init(self.allocator);
        for (0..self.counts.capacity) |i| {
            if (self.counts.entries[i].occupied) {
                var j: usize = 0;
                while (j < self.counts.entries[i].value) : (j += 1) {
                    mutable.add(self.counts.entries[i].key);
                }
            }
        }
        return mutable;
    }
};

test "ImmutableF64HashBag: of and occurrences" {
    var ib = ImmutableF64HashBag.of(std.testing.allocator, &[_]f64{ 1.0, 1.0, 2.0 });
    defer ib.deinit();
    try std.testing.expectEqual(@as(usize, 2), ib.occurrencesOf(1.0));
    try std.testing.expectEqual(@as(usize, 1), ib.occurrencesOf(2.0));
    try std.testing.expectEqual(@as(usize, 3), ib.totalSize());
    try std.testing.expectEqual(@as(usize, 2), ib.sizeDistinct());
}

test "ImmutableF64HashBag: toMutable independence" {
    var ib = ImmutableF64HashBag.of(std.testing.allocator, &[_]f64{ 1.0, 1.0 });
    defer ib.deinit();
    var mb = ib.toMutable();
    defer mb.deinit();
    mb.add(2.0);
    try std.testing.expectEqual(@as(usize, 2), ib.totalSize());
    try std.testing.expectEqual(@as(usize, 3), mb.totalSize());
}
