// Code generated by mapdb-codegen. DO NOT EDIT.

const std = @import("std");
const Allocator = std.mem.Allocator;
const I16ArrayDeque = @import("../deque/i16_array_deque.zig").I16ArrayDeque;

/// Immutable deque of `i16` values, backed by an owned allocated slice.
/// All "mutating" operations return new immutable deques.
pub const ImmutableI16ArrayDeque = struct {
    items: []const i16,
    allocator: Allocator,

    pub fn of(allocator: Allocator, values: []const i16) ImmutableI16ArrayDeque {
        const owned = allocator.dupe(i16, values) catch @panic("out of memory");
        return .{ .items = owned, .allocator = allocator };
    }

    pub fn fromMutable(allocator: Allocator, mutable: *const I16ArrayDeque) ImmutableI16ArrayDeque {
        return of(allocator, mutable.items.items);
    }

    pub fn deinit(self: *ImmutableI16ArrayDeque) void {
        self.allocator.free(self.items);
    }

    pub fn peekFirst(self: *const ImmutableI16ArrayDeque) ?i16 {
        if (self.items.len == 0) return null;
        return self.items[0];
    }

    pub fn peekLast(self: *const ImmutableI16ArrayDeque) ?i16 {
        if (self.items.len == 0) return null;
        return self.items[self.items.len - 1];
    }

    pub fn len(self: *const ImmutableI16ArrayDeque) usize {
        return self.items.len;
    }
    pub fn isEmpty(self: *const ImmutableI16ArrayDeque) bool {
        return self.items.len == 0;
    }

    pub fn contains(self: *const ImmutableI16ArrayDeque, value: i16) bool {
        for (self.items) |item| {
            if (item == value) return true;
        }
        return false;
    }

    pub fn toSlice(self: *const ImmutableI16ArrayDeque) []const i16 {
        return self.items;
    }

    /// Returns a new immutable deque with `value` prepended at the front.
    pub fn withFirst(self: *const ImmutableI16ArrayDeque, value: i16) ImmutableI16ArrayDeque {
        const new_items = self.allocator.alloc(i16, self.items.len + 1) catch @panic("out of memory");
        new_items[0] = value;
        @memcpy(new_items[1..], self.items);
        return .{ .items = new_items, .allocator = self.allocator };
    }

    /// Returns a new immutable deque with `value` appended at the back.
    pub fn withLast(self: *const ImmutableI16ArrayDeque, value: i16) ImmutableI16ArrayDeque {
        const new_items = self.allocator.alloc(i16, self.items.len + 1) catch @panic("out of memory");
        @memcpy(new_items[0..self.items.len], self.items);
        new_items[self.items.len] = value;
        return .{ .items = new_items, .allocator = self.allocator };
    }

    /// Returns a new deque without the front element, and the removed value.
    pub fn withoutFirst(self: *const ImmutableI16ArrayDeque) ?struct { deque: ImmutableI16ArrayDeque, value: i16 } {
        if (self.items.len == 0) return null;
        const first = self.items[0];
        const new_items = self.allocator.dupe(i16, self.items[1..]) catch @panic("out of memory");
        return .{
            .deque = .{ .items = new_items, .allocator = self.allocator },
            .value = first,
        };
    }

    /// Returns a new deque without the back element, and the removed value.
    pub fn withoutLast(self: *const ImmutableI16ArrayDeque) ?struct { deque: ImmutableI16ArrayDeque, value: i16 } {
        if (self.items.len == 0) return null;
        const last = self.items[self.items.len - 1];
        const new_items = self.allocator.dupe(i16, self.items[0 .. self.items.len - 1]) catch @panic("out of memory");
        return .{
            .deque = .{ .items = new_items, .allocator = self.allocator },
            .value = last,
        };
    }

    pub fn forEach(self: *const ImmutableI16ArrayDeque, f: *const fn (i16) void) void {
        for (self.items) |value| f(value);
    }

    pub fn toMutable(self: *const ImmutableI16ArrayDeque) I16ArrayDeque {
        return I16ArrayDeque.of(self.allocator, self.items);
    }

    pub fn eql(self: *const ImmutableI16ArrayDeque, other: *const ImmutableI16ArrayDeque) bool {
        if (self.items.len != other.items.len) return false;
        for (self.items, other.items) |a, b| {
            if (!(a == b)) return false;
        }
        return true;
    }
};

test "ImmutableI16ArrayDeque: of and peek" {
    var d = ImmutableI16ArrayDeque.of(std.testing.allocator, &[_]i16{ 1, 2, 3 });
    defer d.deinit();
    try std.testing.expectEqual(@as(usize, 3), d.len());
    try std.testing.expectEqual(@as(?i16, 1), d.peekFirst());
    try std.testing.expectEqual(@as(?i16, 3), d.peekLast());
}

test "ImmutableI16ArrayDeque: persistent withFirst/withLast" {
    var d1 = ImmutableI16ArrayDeque.of(std.testing.allocator, &[_]i16{2});
    defer d1.deinit();
    var d2 = d1.withFirst(1);
    defer d2.deinit();
    var d3 = d2.withLast(3);
    defer d3.deinit();
    try std.testing.expectEqual(@as(usize, 1), d1.len());
    try std.testing.expectEqual(@as(usize, 3), d3.len());
    try std.testing.expectEqual(@as(?i16, 1), d3.peekFirst());
    try std.testing.expectEqual(@as(?i16, 3), d3.peekLast());
}

test "ImmutableI16ArrayDeque: withoutFirst/withoutLast" {
    var d = ImmutableI16ArrayDeque.of(std.testing.allocator, &[_]i16{ 1, 2, 3 });
    defer d.deinit();
    const r1 = d.withoutFirst().?;
    var d2 = r1.deque;
    defer d2.deinit();
    try std.testing.expectEqual(1, r1.value);
    try std.testing.expectEqual(@as(usize, 2), d2.len());

    const r2 = d.withoutLast().?;
    var d3 = r2.deque;
    defer d3.deinit();
    try std.testing.expectEqual(3, r2.value);
    try std.testing.expectEqual(@as(usize, 2), d3.len());

    // Original untouched
    try std.testing.expectEqual(@as(usize, 3), d.len());
}

test "ImmutableI16ArrayDeque: fromMutable and toMutable independence" {
    var ml = I16ArrayDeque.init(std.testing.allocator);
    defer ml.deinit();
    ml.addLast(1);
    ml.addLast(2);
    var il = ImmutableI16ArrayDeque.fromMutable(std.testing.allocator, &ml);
    defer il.deinit();
    var ml2 = il.toMutable();
    defer ml2.deinit();
    ml2.addLast(3);
    try std.testing.expectEqual(@as(usize, 2), il.len());
    try std.testing.expectEqual(@as(usize, 3), ml2.len());
}

test "ImmutableI16ArrayDeque: eql and contains" {
    var a = ImmutableI16ArrayDeque.of(std.testing.allocator, &[_]i16{ 1, 2 });
    defer a.deinit();
    var b = ImmutableI16ArrayDeque.of(std.testing.allocator, &[_]i16{ 1, 2 });
    defer b.deinit();
    try std.testing.expect(a.eql(&b));
    try std.testing.expect(a.contains(1));
}
