// Code generated by mapdb-codegen. DO NOT EDIT.

const std = @import("std");
const Allocator = std.mem.Allocator;
const I8HashSet = @import("../hashset/i8_hash_set.zig").I8HashSet;

/// Immutable set of unique `i8` values, backed by an owned allocated slice.
///
/// All operations are read-only. Call `toMutable()` for an independent mutable copy.
pub const ImmutableI8HashSet = struct {
    items: []const i8,
    allocator: Allocator,

    pub fn of(allocator: Allocator, values: []const i8) ImmutableI8HashSet {
        // Deduplicate
        var mutable = I8HashSet.init(allocator);
        for (values) |val| _ = mutable.add(val);
        // Snapshot to owned slice
        var buf: std.ArrayListUnmanaged(i8) = .empty;
        for (0..mutable.inner.capacity) |i| {
            if (mutable.inner.entries[i].occupied) buf.append(allocator, mutable.inner.entries[i].key) catch @panic("out of memory");
        }
        mutable.deinit();
        const owned = buf.toOwnedSlice(allocator) catch @panic("out of memory");
        return .{ .items = owned, .allocator = allocator };
    }

    pub fn fromMutable(allocator: Allocator, mutable: *const I8HashSet) ImmutableI8HashSet {
        var buf: std.ArrayListUnmanaged(i8) = .empty;
        for (0..mutable.inner.capacity) |i| {
            if (mutable.inner.entries[i].occupied) buf.append(allocator, mutable.inner.entries[i].key) catch @panic("out of memory");
        }
        const owned = buf.toOwnedSlice(allocator) catch @panic("out of memory");
        return .{ .items = owned, .allocator = allocator };
    }

    pub fn deinit(self: *ImmutableI8HashSet) void {
        self.allocator.free(self.items);
    }

    pub fn len(self: *const ImmutableI8HashSet) usize {
        return self.items.len;
    }

    pub fn isEmpty(self: *const ImmutableI8HashSet) bool {
        return self.items.len == 0;
    }

    pub fn contains(self: *const ImmutableI8HashSet, value: i8) bool {
        for (self.items) |item| {
            if (item == value) return true;
        }
        return false;
    }

    pub fn toSlice(self: *const ImmutableI8HashSet) []const i8 {
        return self.items;
    }

    pub fn toMutable(self: *const ImmutableI8HashSet) I8HashSet {
        return I8HashSet.of(self.allocator, self.items);
    }

    pub fn eql(self: *const ImmutableI8HashSet, other: *const ImmutableI8HashSet) bool {
        if (self.items.len != other.items.len) return false;
        for (self.items) |item| {
            if (!other.contains(item)) return false;
        }
        return true;
    }
};

test "ImmutableI8HashSet: of and contains" {
    var il = ImmutableI8HashSet.of(std.testing.allocator, &[_]i8{ 1, 2, 1 });
    defer il.deinit();
    try std.testing.expectEqual(@as(usize, 2), il.len());
    try std.testing.expect(il.contains(1));
}

test "ImmutableI8HashSet: toMutable independence" {
    var il = ImmutableI8HashSet.of(std.testing.allocator, &[_]i8{ 1, 2 });
    defer il.deinit();
    var ml = il.toMutable();
    defer ml.deinit();
    _ = ml.add(3);
    try std.testing.expectEqual(@as(usize, 2), il.len());
    try std.testing.expectEqual(@as(usize, 3), ml.len());
}
