// Code generated by mapdb-codegen. DO NOT EDIT.

const std = @import("std");

/// Immutable pair of (`bool`, `i32`).
pub const BoolI32Pair = struct {
    first: bool,
    second: i32,

    pub fn new(first: bool, second: i32) BoolI32Pair {
        return .{ .first = first, .second = second };
    }

    pub fn one(self: BoolI32Pair) bool {
        return self.first;
    }

    pub fn two(self: BoolI32Pair) i32 {
        return self.second;
    }

    pub fn swap(self: BoolI32Pair) I32BoolPair {
        return .{ .first = self.second, .second = self.first };
    }

    pub fn eql(self: BoolI32Pair, other: BoolI32Pair) bool {
        return (self.first == other.first) and (self.second == other.second);
    }

    pub fn format(self: BoolI32Pair, comptime _: []const u8, _: std.fmt.FormatOptions, writer: anytype) !void {
        try std.fmt.format(writer, "({}, {})", .{ self.first, self.second });
    }
};

const I32BoolPair = @import("i32_bool_pair.zig").I32BoolPair;

test "BoolI32Pair: one and two" {
    const p = BoolI32Pair.new(true, 2);
    try std.testing.expectEqual(true, p.one());
    try std.testing.expectEqual(2, p.two());
}

test "BoolI32Pair: eql" {
    const p1 = BoolI32Pair.new(true, 2);
    const p2 = BoolI32Pair.new(true, 2);
    const p3 = BoolI32Pair.new(false, 1);
    try std.testing.expect(p1.eql(p2));
    try std.testing.expect(!p1.eql(p3));
}
