// Code generated by mapdb-codegen. DO NOT EDIT.

const std = @import("std");

/// Immutable pair of (`u21`, `bool`).
pub const CharBoolPair = struct {
    first: u21,
    second: bool,

    pub fn new(first: u21, second: bool) CharBoolPair {
        return .{ .first = first, .second = second };
    }

    pub fn one(self: CharBoolPair) u21 {
        return self.first;
    }

    pub fn two(self: CharBoolPair) bool {
        return self.second;
    }

    pub fn swap(self: CharBoolPair) BoolCharPair {
        return .{ .first = self.second, .second = self.first };
    }

    pub fn eql(self: CharBoolPair, other: CharBoolPair) bool {
        return (self.first == other.first) and (self.second == other.second);
    }

    pub fn format(self: CharBoolPair, comptime _: []const u8, _: std.fmt.FormatOptions, writer: anytype) !void {
        try std.fmt.format(writer, "({}, {})", .{ self.first, self.second });
    }
};

const BoolCharPair = @import("bool_char_pair.zig").BoolCharPair;

test "CharBoolPair: one and two" {
    const p = CharBoolPair.new('a', false);
    try std.testing.expectEqual('a', p.one());
    try std.testing.expectEqual(false, p.two());
}

test "CharBoolPair: eql" {
    const p1 = CharBoolPair.new('a', false);
    const p2 = CharBoolPair.new('a', false);
    const p3 = CharBoolPair.new('b', true);
    try std.testing.expect(p1.eql(p2));
    try std.testing.expect(!p1.eql(p3));
}
