// Code generated by mapdb-codegen. DO NOT EDIT.

const std = @import("std");

/// Immutable pair of (`u21`, `i8`).
pub const CharI8Pair = struct {
    first: u21,
    second: i8,

    pub fn new(first: u21, second: i8) CharI8Pair {
        return .{ .first = first, .second = second };
    }

    pub fn one(self: CharI8Pair) u21 {
        return self.first;
    }

    pub fn two(self: CharI8Pair) i8 {
        return self.second;
    }

    pub fn swap(self: CharI8Pair) I8CharPair {
        return .{ .first = self.second, .second = self.first };
    }

    pub fn eql(self: CharI8Pair, other: CharI8Pair) bool {
        return (self.first == other.first) and (self.second == other.second);
    }

    pub fn format(self: CharI8Pair, comptime _: []const u8, _: std.fmt.FormatOptions, writer: anytype) !void {
        try std.fmt.format(writer, "({}, {})", .{ self.first, self.second });
    }
};

const I8CharPair = @import("i8_char_pair.zig").I8CharPair;

test "CharI8Pair: one and two" {
    const p = CharI8Pair.new('a', 2);
    try std.testing.expectEqual('a', p.one());
    try std.testing.expectEqual(2, p.two());
}

test "CharI8Pair: eql" {
    const p1 = CharI8Pair.new('a', 2);
    const p2 = CharI8Pair.new('a', 2);
    const p3 = CharI8Pair.new('b', 1);
    try std.testing.expect(p1.eql(p2));
    try std.testing.expect(!p1.eql(p3));
}
