// Code generated by mapdb-codegen. DO NOT EDIT.

const std = @import("std");

/// Immutable pair of (`f32`, `f32`).
pub const F32F32Pair = struct {
    first: f32,
    second: f32,

    pub fn new(first: f32, second: f32) F32F32Pair {
        return .{ .first = first, .second = second };
    }

    pub fn one(self: F32F32Pair) f32 {
        return self.first;
    }

    pub fn two(self: F32F32Pair) f32 {
        return self.second;
    }

    pub fn swap(self: F32F32Pair) F32F32Pair {
        return .{ .first = self.second, .second = self.first };
    }

    pub fn eql(self: F32F32Pair, other: F32F32Pair) bool {
        return (@as(u32, @bitCast(self.first)) == @as(u32, @bitCast(other.first))) and (@as(u32, @bitCast(self.second)) == @as(u32, @bitCast(other.second)));
    }

    pub fn format(self: F32F32Pair, comptime _: []const u8, _: std.fmt.FormatOptions, writer: anytype) !void {
        try std.fmt.format(writer, "({}, {})", .{ self.first, self.second });
    }
};

// Self-pair: swap returns same type

test "F32F32Pair: one and two" {
    const p = F32F32Pair.new(1.0, 2.0);
    try std.testing.expectEqual(1.0, p.one());
    try std.testing.expectEqual(2.0, p.two());
}

test "F32F32Pair: eql" {
    const p1 = F32F32Pair.new(1.0, 2.0);
    const p2 = F32F32Pair.new(1.0, 2.0);
    const p3 = F32F32Pair.new(2.0, 1.0);
    try std.testing.expect(p1.eql(p2));
    try std.testing.expect(!p1.eql(p3));
}
