// Code generated by mapdb-codegen. DO NOT EDIT.

const std = @import("std");

/// Immutable pair of (`i16`, `i16`).
pub const I16I16Pair = struct {
    first: i16,
    second: i16,

    pub fn new(first: i16, second: i16) I16I16Pair {
        return .{ .first = first, .second = second };
    }

    pub fn one(self: I16I16Pair) i16 {
        return self.first;
    }

    pub fn two(self: I16I16Pair) i16 {
        return self.second;
    }

    pub fn swap(self: I16I16Pair) I16I16Pair {
        return .{ .first = self.second, .second = self.first };
    }

    pub fn eql(self: I16I16Pair, other: I16I16Pair) bool {
        return (self.first == other.first) and (self.second == other.second);
    }

    pub fn format(self: I16I16Pair, comptime _: []const u8, _: std.fmt.FormatOptions, writer: anytype) !void {
        try std.fmt.format(writer, "({}, {})", .{ self.first, self.second });
    }
};

// Self-pair: swap returns same type

test "I16I16Pair: one and two" {
    const p = I16I16Pair.new(1, 2);
    try std.testing.expectEqual(1, p.one());
    try std.testing.expectEqual(2, p.two());
}

test "I16I16Pair: eql" {
    const p1 = I16I16Pair.new(1, 2);
    const p2 = I16I16Pair.new(1, 2);
    const p3 = I16I16Pair.new(2, 1);
    try std.testing.expect(p1.eql(p2));
    try std.testing.expect(!p1.eql(p3));
}
