// Code generated by mapdb-codegen. DO NOT EDIT.

const std = @import("std");

/// Immutable pair of (`i32`, `u21`).
pub const I32CharPair = struct {
    first: i32,
    second: u21,

    pub fn new(first: i32, second: u21) I32CharPair {
        return .{ .first = first, .second = second };
    }

    pub fn one(self: I32CharPair) i32 {
        return self.first;
    }

    pub fn two(self: I32CharPair) u21 {
        return self.second;
    }

    pub fn swap(self: I32CharPair) CharI32Pair {
        return .{ .first = self.second, .second = self.first };
    }

    pub fn eql(self: I32CharPair, other: I32CharPair) bool {
        return (self.first == other.first) and (self.second == other.second);
    }

    pub fn format(self: I32CharPair, comptime _: []const u8, _: std.fmt.FormatOptions, writer: anytype) !void {
        try std.fmt.format(writer, "({}, {})", .{ self.first, self.second });
    }
};

const CharI32Pair = @import("char_i32_pair.zig").CharI32Pair;

test "I32CharPair: one and two" {
    const p = I32CharPair.new(1, 'b');
    try std.testing.expectEqual(1, p.one());
    try std.testing.expectEqual('b', p.two());
}

test "I32CharPair: eql" {
    const p1 = I32CharPair.new(1, 'b');
    const p2 = I32CharPair.new(1, 'b');
    const p3 = I32CharPair.new(2, 'a');
    try std.testing.expect(p1.eql(p2));
    try std.testing.expect(!p1.eql(p3));
}
