// Code generated by mapdb-codegen. DO NOT EDIT.

const std = @import("std");

/// Immutable pair of (`i32`, `f32`).
pub const I32F32Pair = struct {
    first: i32,
    second: f32,

    pub fn new(first: i32, second: f32) I32F32Pair {
        return .{ .first = first, .second = second };
    }

    pub fn one(self: I32F32Pair) i32 {
        return self.first;
    }

    pub fn two(self: I32F32Pair) f32 {
        return self.second;
    }

    pub fn swap(self: I32F32Pair) F32I32Pair {
        return .{ .first = self.second, .second = self.first };
    }

    pub fn eql(self: I32F32Pair, other: I32F32Pair) bool {
        return (self.first == other.first) and (@as(u32, @bitCast(self.second)) == @as(u32, @bitCast(other.second)));
    }

    pub fn format(self: I32F32Pair, comptime _: []const u8, _: std.fmt.FormatOptions, writer: anytype) !void {
        try std.fmt.format(writer, "({}, {})", .{ self.first, self.second });
    }
};

const F32I32Pair = @import("f32_i32_pair.zig").F32I32Pair;

test "I32F32Pair: one and two" {
    const p = I32F32Pair.new(1, 2.0);
    try std.testing.expectEqual(1, p.one());
    try std.testing.expectEqual(2.0, p.two());
}

test "I32F32Pair: eql" {
    const p1 = I32F32Pair.new(1, 2.0);
    const p2 = I32F32Pair.new(1, 2.0);
    const p3 = I32F32Pair.new(2, 1.0);
    try std.testing.expect(p1.eql(p2));
    try std.testing.expect(!p1.eql(p3));
}
