// Code generated by mapdb-codegen. DO NOT EDIT.

const std = @import("std");

/// Immutable pair of (`i8`, `i32`).
pub const I8I32Pair = struct {
    first: i8,
    second: i32,

    pub fn new(first: i8, second: i32) I8I32Pair {
        return .{ .first = first, .second = second };
    }

    pub fn one(self: I8I32Pair) i8 {
        return self.first;
    }

    pub fn two(self: I8I32Pair) i32 {
        return self.second;
    }

    pub fn swap(self: I8I32Pair) I32I8Pair {
        return .{ .first = self.second, .second = self.first };
    }

    pub fn eql(self: I8I32Pair, other: I8I32Pair) bool {
        return (self.first == other.first) and (self.second == other.second);
    }

    pub fn format(self: I8I32Pair, comptime _: []const u8, _: std.fmt.FormatOptions, writer: anytype) !void {
        try std.fmt.format(writer, "({}, {})", .{ self.first, self.second });
    }
};

const I32I8Pair = @import("i32_i8_pair.zig").I32I8Pair;

test "I8I32Pair: one and two" {
    const p = I8I32Pair.new(1, 2);
    try std.testing.expectEqual(1, p.one());
    try std.testing.expectEqual(2, p.two());
}

test "I8I32Pair: eql" {
    const p1 = I8I32Pair.new(1, 2);
    const p2 = I8I32Pair.new(1, 2);
    const p3 = I8I32Pair.new(2, 1);
    try std.testing.expect(p1.eql(p2));
    try std.testing.expect(!p1.eql(p3));
}
