// Code generated by mapdb-codegen. DO NOT EDIT.

const std = @import("std");

/// Immutable pair of (`i8`, `i8`).
pub const I8I8Pair = struct {
    first: i8,
    second: i8,

    pub fn new(first: i8, second: i8) I8I8Pair {
        return .{ .first = first, .second = second };
    }

    pub fn one(self: I8I8Pair) i8 {
        return self.first;
    }

    pub fn two(self: I8I8Pair) i8 {
        return self.second;
    }

    pub fn swap(self: I8I8Pair) I8I8Pair {
        return .{ .first = self.second, .second = self.first };
    }

    pub fn eql(self: I8I8Pair, other: I8I8Pair) bool {
        return (self.first == other.first) and (self.second == other.second);
    }

    pub fn format(self: I8I8Pair, comptime _: []const u8, _: std.fmt.FormatOptions, writer: anytype) !void {
        try std.fmt.format(writer, "({}, {})", .{ self.first, self.second });
    }
};

// Self-pair: swap returns same type

test "I8I8Pair: one and two" {
    const p = I8I8Pair.new(1, 2);
    try std.testing.expectEqual(1, p.one());
    try std.testing.expectEqual(2, p.two());
}

test "I8I8Pair: eql" {
    const p1 = I8I8Pair.new(1, 2);
    const p2 = I8I8Pair.new(1, 2);
    const p3 = I8I8Pair.new(2, 1);
    try std.testing.expect(p1.eql(p2));
    try std.testing.expect(!p1.eql(p3));
}
