// Code generated by mapdb-codegen. DO NOT EDIT.

const std = @import("std");

/// Comptime interface for read-only maps from `bool` keys to `f64` values.
///
/// Equivalent to:
///   Go:   BoolF64MapIterable interface
///   Rust: BoolF64Map trait
///   Java: BoolF64Map interface
pub fn assertBoolF64Map(comptime T: type) void {
    comptime {
        if (!@hasDecl(T, "len")) @compileError(@typeName(T) ++ " missing len()");
        if (!@hasDecl(T, "isEmpty")) @compileError(@typeName(T) ++ " missing isEmpty()");
        if (!@hasDecl(T, "containsKey")) @compileError(@typeName(T) ++ " missing containsKey()");
        if (!@hasDecl(T, "get")) @compileError(@typeName(T) ++ " missing get()");
    }
}

/// Comptime interface for mutable maps from `bool` to `f64`.
pub fn assertBoolF64MutableMap(comptime T: type) void {
    assertBoolF64Map(T);
    comptime {
        if (!@hasDecl(T, "put")) @compileError(@typeName(T) ++ " missing put()");
        if (!@hasDecl(T, "remove")) @compileError(@typeName(T) ++ " missing remove()");
        if (!@hasDecl(T, "clear")) @compileError(@typeName(T) ++ " missing clear()");
    }
}

// Compile-time verification: every concrete `bool` → `f64` map type
// satisfies the matching read-only and (where applicable) mutable interface.
//
// Imports go through per-package index files — the index is the swap point
// for alternative implementations. See docs/zig/interface-redesign.md.
comptime {
    const hashmap = @import("../hashmap/hashmap.zig");
    const treemap = @import("../treemap/treemap.zig");
    const immutable = @import("../immutable/immutable.zig");

    const HashMap = hashmap.bool_f64_hash_map.BoolF64HashMap;
    assertBoolF64MutableMap(HashMap);

    const TreeMap = treemap.bool_f64_tree_map.BoolF64TreeMap;
    assertBoolF64MutableMap(TreeMap);

    const HashBiMap = hashmap.bool_f64_hash_bi_map.BoolF64HashBiMap;
    assertBoolF64MutableMap(HashBiMap);

    const ImmutableHashMap = immutable.immutable_bool_f64_hash_map.ImmutableBoolF64HashMap;
    assertBoolF64Map(ImmutableHashMap);
}
