// Code generated by mapdb-codegen. DO NOT EDIT.

const std = @import("std");

/// Comptime interface for read-only maps from `u21` keys to `i16` values.
///
/// Equivalent to:
///   Go:   CharI16MapIterable interface
///   Rust: CharI16Map trait
///   Java: CharI16Map interface
pub fn assertCharI16Map(comptime T: type) void {
    comptime {
        if (!@hasDecl(T, "len")) @compileError(@typeName(T) ++ " missing len()");
        if (!@hasDecl(T, "isEmpty")) @compileError(@typeName(T) ++ " missing isEmpty()");
        if (!@hasDecl(T, "containsKey")) @compileError(@typeName(T) ++ " missing containsKey()");
        if (!@hasDecl(T, "get")) @compileError(@typeName(T) ++ " missing get()");
    }
}

/// Comptime interface for mutable maps from `u21` to `i16`.
pub fn assertCharI16MutableMap(comptime T: type) void {
    assertCharI16Map(T);
    comptime {
        if (!@hasDecl(T, "put")) @compileError(@typeName(T) ++ " missing put()");
        if (!@hasDecl(T, "remove")) @compileError(@typeName(T) ++ " missing remove()");
        if (!@hasDecl(T, "clear")) @compileError(@typeName(T) ++ " missing clear()");
    }
}

// Compile-time verification: every concrete `u21` → `i16` map type
// satisfies the matching read-only and (where applicable) mutable interface.
//
// Imports go through per-package index files — the index is the swap point
// for alternative implementations. See docs/zig/interface-redesign.md.
comptime {
    const hashmap = @import("../hashmap/hashmap.zig");
    const treemap = @import("../treemap/treemap.zig");
    const immutable = @import("../immutable/immutable.zig");

    const HashMap = hashmap.char_i16_hash_map.CharI16HashMap;
    assertCharI16MutableMap(HashMap);

    const TreeMap = treemap.char_i16_tree_map.CharI16TreeMap;
    assertCharI16MutableMap(TreeMap);

    const HashBiMap = hashmap.char_i16_hash_bi_map.CharI16HashBiMap;
    assertCharI16MutableMap(HashBiMap);

    const ImmutableHashMap = immutable.immutable_char_i16_hash_map.ImmutableCharI16HashMap;
    assertCharI16Map(ImmutableHashMap);
}
