// Code generated by mapdb-codegen. DO NOT EDIT.

const std = @import("std");

/// Comptime interface for read-only maps from `u21` keys to `f64` values.
///
/// Equivalent to:
///   Go:   CharF64MapIterable interface
///   Rust: CharF64Map trait
///   Java: CharF64Map interface
pub fn assertCharF64Map(comptime T: type) void {
    comptime {
        if (!@hasDecl(T, "len")) @compileError(@typeName(T) ++ " missing len()");
        if (!@hasDecl(T, "isEmpty")) @compileError(@typeName(T) ++ " missing isEmpty()");
        if (!@hasDecl(T, "containsKey")) @compileError(@typeName(T) ++ " missing containsKey()");
        if (!@hasDecl(T, "get")) @compileError(@typeName(T) ++ " missing get()");
    }
}

/// Comptime interface for mutable maps from `u21` to `f64`.
pub fn assertCharF64MutableMap(comptime T: type) void {
    assertCharF64Map(T);
    comptime {
        if (!@hasDecl(T, "put")) @compileError(@typeName(T) ++ " missing put()");
        if (!@hasDecl(T, "remove")) @compileError(@typeName(T) ++ " missing remove()");
        if (!@hasDecl(T, "clear")) @compileError(@typeName(T) ++ " missing clear()");
    }
}

// Compile-time verification: every concrete `u21` → `f64` map type
// satisfies the matching read-only and (where applicable) mutable interface.
//
// Imports go through per-package index files — the index is the swap point
// for alternative implementations. See docs/zig/interface-redesign.md.
comptime {
    const hashmap = @import("../hashmap/hashmap.zig");
    const treemap = @import("../treemap/treemap.zig");
    const immutable = @import("../immutable/immutable.zig");

    const HashMap = hashmap.char_f64_hash_map.CharF64HashMap;
    assertCharF64MutableMap(HashMap);

    const TreeMap = treemap.char_f64_tree_map.CharF64TreeMap;
    assertCharF64MutableMap(TreeMap);

    const HashBiMap = hashmap.char_f64_hash_bi_map.CharF64HashBiMap;
    assertCharF64MutableMap(HashBiMap);

    const ImmutableHashMap = immutable.immutable_char_f64_hash_map.ImmutableCharF64HashMap;
    assertCharF64Map(ImmutableHashMap);
}
