// Code generated by mapdb-codegen. DO NOT EDIT.

const std = @import("std");

/// Comptime interface for read-only maps from `u21` keys to `f32` values.
///
/// Equivalent to:
///   Go:   CharF32MapIterable interface
///   Rust: CharF32Map trait
///   Java: CharF32Map interface
pub fn assertCharF32Map(comptime T: type) void {
    comptime {
        if (!@hasDecl(T, "len")) @compileError(@typeName(T) ++ " missing len()");
        if (!@hasDecl(T, "isEmpty")) @compileError(@typeName(T) ++ " missing isEmpty()");
        if (!@hasDecl(T, "containsKey")) @compileError(@typeName(T) ++ " missing containsKey()");
        if (!@hasDecl(T, "get")) @compileError(@typeName(T) ++ " missing get()");
    }
}

/// Comptime interface for mutable maps from `u21` to `f32`.
pub fn assertCharF32MutableMap(comptime T: type) void {
    assertCharF32Map(T);
    comptime {
        if (!@hasDecl(T, "put")) @compileError(@typeName(T) ++ " missing put()");
        if (!@hasDecl(T, "remove")) @compileError(@typeName(T) ++ " missing remove()");
        if (!@hasDecl(T, "clear")) @compileError(@typeName(T) ++ " missing clear()");
    }
}

// Compile-time verification: every concrete `u21` → `f32` map type
// satisfies the matching read-only and (where applicable) mutable interface.
//
// Imports go through per-package index files — the index is the swap point
// for alternative implementations. See docs/zig/interface-redesign.md.
comptime {
    const hashmap = @import("../hashmap/hashmap.zig");
    const treemap = @import("../treemap/treemap.zig");
    const immutable = @import("../immutable/immutable.zig");

    const HashMap = hashmap.char_f32_hash_map.CharF32HashMap;
    assertCharF32MutableMap(HashMap);

    const TreeMap = treemap.char_f32_tree_map.CharF32TreeMap;
    assertCharF32MutableMap(TreeMap);

    const HashBiMap = hashmap.char_f32_hash_bi_map.CharF32HashBiMap;
    assertCharF32MutableMap(HashBiMap);

    const ImmutableHashMap = immutable.immutable_char_f32_hash_map.ImmutableCharF32HashMap;
    assertCharF32Map(ImmutableHashMap);
}
