// Code generated by mapdb-codegen. DO NOT EDIT.

const std = @import("std");

/// Comptime interface for read-only maps from `f32` keys to `i32` values.
///
/// Equivalent to:
///   Go:   F32I32MapIterable interface
///   Rust: F32I32Map trait
///   Java: F32I32Map interface
pub fn assertF32I32Map(comptime T: type) void {
    comptime {
        if (!@hasDecl(T, "len")) @compileError(@typeName(T) ++ " missing len()");
        if (!@hasDecl(T, "isEmpty")) @compileError(@typeName(T) ++ " missing isEmpty()");
        if (!@hasDecl(T, "containsKey")) @compileError(@typeName(T) ++ " missing containsKey()");
        if (!@hasDecl(T, "get")) @compileError(@typeName(T) ++ " missing get()");
    }
}

/// Comptime interface for mutable maps from `f32` to `i32`.
pub fn assertF32I32MutableMap(comptime T: type) void {
    assertF32I32Map(T);
    comptime {
        if (!@hasDecl(T, "put")) @compileError(@typeName(T) ++ " missing put()");
        if (!@hasDecl(T, "remove")) @compileError(@typeName(T) ++ " missing remove()");
        if (!@hasDecl(T, "clear")) @compileError(@typeName(T) ++ " missing clear()");
    }
}

// Compile-time verification: every concrete `f32` → `i32` map type
// satisfies the matching read-only and (where applicable) mutable interface.
//
// Imports go through per-package index files — the index is the swap point
// for alternative implementations. See docs/zig/interface-redesign.md.
comptime {
    const hashmap = @import("../hashmap/hashmap.zig");
    const treemap = @import("../treemap/treemap.zig");
    const immutable = @import("../immutable/immutable.zig");

    const HashMap = hashmap.f32_i32_hash_map.F32I32HashMap;
    assertF32I32MutableMap(HashMap);

    const TreeMap = treemap.f32_i32_tree_map.F32I32TreeMap;
    assertF32I32MutableMap(TreeMap);

    const HashBiMap = hashmap.f32_i32_hash_bi_map.F32I32HashBiMap;
    assertF32I32MutableMap(HashBiMap);

    const ImmutableHashMap = immutable.immutable_f32_i32_hash_map.ImmutableF32I32HashMap;
    assertF32I32Map(ImmutableHashMap);
}
