// Code generated by mapdb-codegen. DO NOT EDIT.

const std = @import("std");

/// Comptime interface for read-only maps from `f64` keys to `f64` values.
///
/// Equivalent to:
///   Go:   F64F64MapIterable interface
///   Rust: F64F64Map trait
///   Java: F64F64Map interface
pub fn assertF64F64Map(comptime T: type) void {
    comptime {
        if (!@hasDecl(T, "len")) @compileError(@typeName(T) ++ " missing len()");
        if (!@hasDecl(T, "isEmpty")) @compileError(@typeName(T) ++ " missing isEmpty()");
        if (!@hasDecl(T, "containsKey")) @compileError(@typeName(T) ++ " missing containsKey()");
        if (!@hasDecl(T, "get")) @compileError(@typeName(T) ++ " missing get()");
    }
}

/// Comptime interface for mutable maps from `f64` to `f64`.
pub fn assertF64F64MutableMap(comptime T: type) void {
    assertF64F64Map(T);
    comptime {
        if (!@hasDecl(T, "put")) @compileError(@typeName(T) ++ " missing put()");
        if (!@hasDecl(T, "remove")) @compileError(@typeName(T) ++ " missing remove()");
        if (!@hasDecl(T, "clear")) @compileError(@typeName(T) ++ " missing clear()");
    }
}

// Compile-time verification: every concrete `f64` → `f64` map type
// satisfies the matching read-only and (where applicable) mutable interface.
//
// Imports go through per-package index files — the index is the swap point
// for alternative implementations. See docs/zig/interface-redesign.md.
comptime {
    const hashmap = @import("../hashmap/hashmap.zig");
    const treemap = @import("../treemap/treemap.zig");
    const immutable = @import("../immutable/immutable.zig");

    const HashMap = hashmap.f64_f64_hash_map.F64F64HashMap;
    assertF64F64MutableMap(HashMap);

    const TreeMap = treemap.f64_f64_tree_map.F64F64TreeMap;
    assertF64F64MutableMap(TreeMap);

    const HashBiMap = hashmap.f64_f64_hash_bi_map.F64F64HashBiMap;
    assertF64F64MutableMap(HashBiMap);

    const ImmutableHashMap = immutable.immutable_f64_f64_hash_map.ImmutableF64F64HashMap;
    assertF64F64Map(ImmutableHashMap);
}
