// Code generated by mapdb-codegen. DO NOT EDIT.

const std = @import("std");

/// Comptime interface for read-only maps from `i64` keys to `i8` values.
///
/// Equivalent to:
///   Go:   I64I8MapIterable interface
///   Rust: I64I8Map trait
///   Java: I64I8Map interface
pub fn assertI64I8Map(comptime T: type) void {
    comptime {
        if (!@hasDecl(T, "len")) @compileError(@typeName(T) ++ " missing len()");
        if (!@hasDecl(T, "isEmpty")) @compileError(@typeName(T) ++ " missing isEmpty()");
        if (!@hasDecl(T, "containsKey")) @compileError(@typeName(T) ++ " missing containsKey()");
        if (!@hasDecl(T, "get")) @compileError(@typeName(T) ++ " missing get()");
    }
}

/// Comptime interface for mutable maps from `i64` to `i8`.
pub fn assertI64I8MutableMap(comptime T: type) void {
    assertI64I8Map(T);
    comptime {
        if (!@hasDecl(T, "put")) @compileError(@typeName(T) ++ " missing put()");
        if (!@hasDecl(T, "remove")) @compileError(@typeName(T) ++ " missing remove()");
        if (!@hasDecl(T, "clear")) @compileError(@typeName(T) ++ " missing clear()");
    }
}

// Compile-time verification: every concrete `i64` → `i8` map type
// satisfies the matching read-only and (where applicable) mutable interface.
//
// Imports go through per-package index files — the index is the swap point
// for alternative implementations. See docs/zig/interface-redesign.md.
comptime {
    const hashmap = @import("../hashmap/hashmap.zig");
    const treemap = @import("../treemap/treemap.zig");
    const immutable = @import("../immutable/immutable.zig");

    const HashMap = hashmap.i64_i8_hash_map.I64I8HashMap;
    assertI64I8MutableMap(HashMap);

    const TreeMap = treemap.i64_i8_tree_map.I64I8TreeMap;
    assertI64I8MutableMap(TreeMap);

    const HashBiMap = hashmap.i64_i8_hash_bi_map.I64I8HashBiMap;
    assertI64I8MutableMap(HashBiMap);

    const ImmutableHashMap = immutable.immutable_i64_i8_hash_map.ImmutableI64I8HashMap;
    assertI64I8Map(ImmutableHashMap);
}
