// Code generated by mapdb-codegen. DO NOT EDIT.

const std = @import("std");

/// A virtual collection representing a range of `i32` values [from, to] with
/// a given step. No elements are materialised in memory.
pub const I32Interval = struct {
    from: i32,
    to: i32,
    step: i32,

    /// Creates an interval from `from` to `to` (inclusive) with the given step.
    pub fn fromToBy(from: i32, to: i32, step: i32) I32Interval {
        std.debug.assert(step != 0); // step must not be zero
        if (from < to) std.debug.assert(step > 0); // step must be positive when from < to
        if (from > to) std.debug.assert(step < 0); // step must be negative when from > to
        return .{ .from = from, .to = to, .step = step };
    }

    /// Creates an interval from `from` to `to` (inclusive) with step 1 or -1.
    pub fn fromTo(from: i32, to: i32) I32Interval {
        const step: i32 = if (from <= to) 1 else -1;
        return .{ .from = from, .to = to, .step = step };
    }

    /// Creates an interval from 1 to `to` (inclusive).
    pub fn oneTo(to: i32) I32Interval {
        return fromTo(1, to);
    }

    /// Creates an interval from 0 to `to` (inclusive).
    pub fn zeroTo(to: i32) I32Interval {
        return fromTo(0, to);
    }

    /// Returns the number of elements in the interval.
    pub fn len(self: *const I32Interval) usize {
        if ((self.step > 0 and self.from > self.to) or (self.step < 0 and self.from < self.to)) {
            return 0;
        }
        const diff: i64 = @as(i64, self.to) - @as(i64, self.from);
        const s: i64 = @as(i64, self.step);
        return @intCast(@divTrunc(diff, s) + 1);
    }

    /// Returns true if the interval is empty.
    pub fn isEmpty(self: *const I32Interval) bool {
        return self.len() == 0;
    }

    /// Returns true if the interval contains the given value.
    pub fn contains(self: *const I32Interval, value: i32) bool {
        if (self.step > 0) {
            return value >= self.from and value <= self.to and @mod(value - self.from, self.step) == 0;
        } else {
            return value <= self.from and value >= self.to and @mod(self.from - value, -self.step) == 0;
        }
    }

    /// Returns the element at the given index, or null if out of bounds.
    pub fn get(self: *const I32Interval, index: usize) ?i32 {
        if (index >= self.len()) return null;
        return self.from + self.step * @as(i32, @intCast(index));
    }

    /// Returns all elements as a slice. Caller must free the returned slice.
    pub fn toSlice(self: *const I32Interval, allocator: std.mem.Allocator) ![]i32 {
        const n = self.len();
        var result = try allocator.alloc(i32, n);
        var i: usize = 0;
        var current = self.from;
        if (self.step > 0) {
            while (current <= self.to) : (i += 1) {
                result[i] = current;
                current += self.step;
            }
        } else {
            while (current >= self.to) : (i += 1) {
                result[i] = current;
                current += self.step;
            }
        }
        return result;
    }

    /// Returns a reversed interval.
    pub fn reversed(self: *const I32Interval) I32Interval {
        return .{ .from = self.to, .to = self.from, .step = -self.step };
    }
};

// ── Tests ──────────────────────────────────────────────────────────────

test "I32Interval fromTo ascending" {
    const iv = I32Interval.fromTo(1, 5);
    try std.testing.expectEqual(@as(usize, 5), iv.len());
    const slice = try iv.toSlice(std.testing.allocator);
    defer std.testing.allocator.free(slice);
    try std.testing.expectEqualSlices(i32, &[_]i32{ 1, 2, 3, 4, 5 }, slice);
}

test "I32Interval fromTo descending" {
    const iv = I32Interval.fromTo(5, 1);
    try std.testing.expectEqual(@as(usize, 5), iv.len());
    const slice = try iv.toSlice(std.testing.allocator);
    defer std.testing.allocator.free(slice);
    try std.testing.expectEqualSlices(i32, &[_]i32{ 5, 4, 3, 2, 1 }, slice);
}

test "I32Interval fromToBy" {
    const iv = I32Interval.fromToBy(0, 10, 2);
    try std.testing.expectEqual(@as(usize, 6), iv.len());
    const slice = try iv.toSlice(std.testing.allocator);
    defer std.testing.allocator.free(slice);
    try std.testing.expectEqualSlices(i32, &[_]i32{ 0, 2, 4, 6, 8, 10 }, slice);
}

test "I32Interval fromToBy negative step" {
    const iv = I32Interval.fromToBy(10, 1, -3);
    try std.testing.expectEqual(@as(usize, 4), iv.len());
    const slice = try iv.toSlice(std.testing.allocator);
    defer std.testing.allocator.free(slice);
    try std.testing.expectEqualSlices(i32, &[_]i32{ 10, 7, 4, 1 }, slice);
}

test "I32Interval single element" {
    const iv = I32Interval.fromTo(3, 3);
    try std.testing.expectEqual(@as(usize, 1), iv.len());
}

test "I32Interval contains" {
    const iv = I32Interval.fromToBy(0, 10, 2);
    try std.testing.expect(iv.contains(0));
    try std.testing.expect(iv.contains(4));
    try std.testing.expect(iv.contains(10));
    try std.testing.expect(!iv.contains(3));
    try std.testing.expect(!iv.contains(11));
}

test "I32Interval get" {
    const iv = I32Interval.fromTo(1, 5);
    try std.testing.expectEqual(@as(?i32, 1), iv.get(0));
    try std.testing.expectEqual(@as(?i32, 5), iv.get(4));
    try std.testing.expectEqual(@as(?i32, null), iv.get(5));
}

test "I32Interval reversed" {
    const iv = I32Interval.fromTo(1, 5);
    const rev = iv.reversed();
    const slice = try rev.toSlice(std.testing.allocator);
    defer std.testing.allocator.free(slice);
    try std.testing.expectEqualSlices(i32, &[_]i32{ 5, 4, 3, 2, 1 }, slice);
}

test "I32Interval oneTo" {
    const iv = I32Interval.oneTo(3);
    const slice = try iv.toSlice(std.testing.allocator);
    defer std.testing.allocator.free(slice);
    try std.testing.expectEqualSlices(i32, &[_]i32{ 1, 2, 3 }, slice);
}

test "I32Interval zeroTo" {
    const iv = I32Interval.zeroTo(3);
    try std.testing.expectEqual(@as(usize, 4), iv.len());
}

test "I32Interval isEmpty" {
    const iv = I32Interval.fromTo(1, 5);
    try std.testing.expect(!iv.isEmpty());
}
