// Copyright (c) 2026 Jan Kotek.
// Derived from Eclipse Collections (Copyright (c) Goldman Sachs and others).
// Licensed under the Eclipse Public License v1.0 and Eclipse Distribution License v1.0.
// See LICENSE-EPL-1.0.txt and LICENSE-EDL-1.0.txt.
// USE AT YOUR OWN RISK — THIS SOFTWARE IS PROVIDED WITHOUT WARRANTY OF ANY KIND.

// Code generated by mapdb-codegen. DO NOT EDIT.

const std = @import("std");
const Allocator = std.mem.Allocator;

/// Configuration for collection allocators.
///
/// All fields default to null, meaning "use the base allocator".
/// Override individual fields to use specialized allocators for
/// different internal data structures (e.g. arena for keys,
/// page allocator for large value buffers).
///
/// Usage:
///   // Simple — one allocator for everything:
///   var list = I32ArrayList.init(gpa.allocator());
///
///   // Advanced — separate allocators for performance:
///   var map = I32I64HashMap.initWithConfig(AllocatorConfig.init(gpa.allocator())
///       .withKeysAllocator(arena.allocator())
///       .withValuesAllocator(page_alloc.allocator()));
pub const AllocatorConfig = struct {
    /// Base allocator used for any internal structure that doesn't
    /// have a specialized allocator override.
    base: Allocator,

    /// Allocator for the primary items buffer (ArrayList, Stack).
    items: ?Allocator = null,

    /// Allocator for key storage (HashSet, HashMap, TreeSet, TreeMap).
    keys: ?Allocator = null,

    /// Allocator for value storage (HashMap, TreeMap).
    values: ?Allocator = null,

    /// Allocator for internal index/bucket arrays (hash tables).
    index: ?Allocator = null,

    /// Allocator for tree nodes and leaves (TreeSet, TreeMap).
    nodes: ?Allocator = null,

    /// Create a config with a single base allocator for everything.
    pub fn init(base: Allocator) AllocatorConfig {
        return .{ .base = base };
    }

    // Builder methods — each returns a modified copy.

    pub fn withItemsAllocator(self: AllocatorConfig, a: Allocator) AllocatorConfig {
        var c = self;
        c.items = a;
        return c;
    }

    pub fn withKeysAllocator(self: AllocatorConfig, a: Allocator) AllocatorConfig {
        var c = self;
        c.keys = a;
        return c;
    }

    pub fn withValuesAllocator(self: AllocatorConfig, a: Allocator) AllocatorConfig {
        var c = self;
        c.values = a;
        return c;
    }

    pub fn withIndexAllocator(self: AllocatorConfig, a: Allocator) AllocatorConfig {
        var c = self;
        c.index = a;
        return c;
    }

    pub fn withNodesAllocator(self: AllocatorConfig, a: Allocator) AllocatorConfig {
        var c = self;
        c.nodes = a;
        return c;
    }

    // Resolved getters — return the specialized allocator if set, else base.

    pub fn itemsAllocator(self: AllocatorConfig) Allocator {
        return self.items orelse self.base;
    }

    pub fn keysAllocator(self: AllocatorConfig) Allocator {
        return self.keys orelse self.base;
    }

    pub fn valuesAllocator(self: AllocatorConfig) Allocator {
        return self.values orelse self.base;
    }

    pub fn indexAllocator(self: AllocatorConfig) Allocator {
        return self.index orelse self.base;
    }

    pub fn nodesAllocator(self: AllocatorConfig) Allocator {
        return self.nodes orelse self.base;
    }
};
