// Code generated by mapdb-codegen. DO NOT EDIT.

const std = @import("std");
const Allocator = std.mem.Allocator;
const AllocatorConfig = @import("../allocator_config.zig").AllocatorConfig;

/// LIFO stack of `i32` values, backed by an ArrayList.
pub const I32ArrayStack = struct {
    items: std.ArrayListUnmanaged(i32) = .empty,
    config: AllocatorConfig,

    pub fn init(allocator: Allocator) I32ArrayStack {
        return .{ .config = AllocatorConfig.init(allocator) };
    }

    pub fn initWithConfig(config: AllocatorConfig) I32ArrayStack {
        return .{ .config = config };
    }

    pub fn deinit(self: *I32ArrayStack) void {
        self.items.deinit(self.config.itemsAllocator());
    }

    pub fn of(allocator: Allocator, values: []const i32) I32ArrayStack {
        var stack = init(allocator);
        stack.items.appendSlice(stack.config.itemsAllocator(), values) catch @panic("out of memory");
        return stack;
    }

    /// Pushes a value onto the top of the stack.
    pub fn push(self: *I32ArrayStack, value: i32) void {
        self.items.append(self.config.itemsAllocator(), value) catch @panic("out of memory");
    }

    /// Removes and returns the top element, or null if empty.
    pub fn pop(self: *I32ArrayStack) ?i32 {
        if (self.items.items.len == 0) return null;
        return self.items.pop();
    }

    /// Returns the top element without removing it, or null if empty.
    pub fn peek(self: *const I32ArrayStack) ?i32 {
        if (self.items.items.len == 0) return null;
        return self.items.items[self.items.items.len - 1];
    }

    /// Returns the element at the given depth from the top (0 = top).
    pub fn peekAt(self: *const I32ArrayStack, depth: usize) ?i32 {
        if (depth >= self.items.items.len) return null;
        return self.items.items[self.items.items.len - 1 - depth];
    }

    pub fn len(self: *const I32ArrayStack) usize {
        return self.items.items.len;
    }

    /// Alias for len() — matches Go/Java naming.
    pub fn size(self: *const I32ArrayStack) usize {
        return self.len();
    }

    pub fn isEmpty(self: *const I32ArrayStack) bool {
        return self.items.items.len == 0;
    }

    pub fn clear(self: *I32ArrayStack) void {
        self.items.clearRetainingCapacity();
    }

    // ---- Fallible capacity reservation ----

    /// Ensures that `additional` more items can be pushed without a
    /// reallocation. See `docs/zig/error-handling.md`.
    pub fn ensureUnusedCapacity(self: *I32ArrayStack, additional: usize) Allocator.Error!void {
        return self.items.ensureUnusedCapacity(self.config.itemsAllocator(), additional);
    }

    /// Ensures the stack's total capacity is at least `new_capacity`.
    pub fn ensureTotalCapacity(self: *I32ArrayStack, new_capacity: usize) Allocator.Error!void {
        return self.items.ensureTotalCapacity(self.config.itemsAllocator(), new_capacity);
    }

    pub fn contains(self: *const I32ArrayStack, value: i32) bool {
        for (self.items.items) |item| {
            if (item == value) return true;
        }
        return false;
    }

    pub fn anySatisfy(self: *const I32ArrayStack, predicate: *const fn (i32) bool) bool {
        for (self.items.items) |item| {
            if (predicate(item)) return true;
        }
        return false;
    }

    pub fn allSatisfy(self: *const I32ArrayStack, predicate: *const fn (i32) bool) bool {
        for (self.items.items) |item| {
            if (!predicate(item)) return false;
        }
        return true;
    }

    // ---- Iteration ----

    /// Calls f for each element (bottom to top).
    pub fn forEach(self: *const I32ArrayStack, f: *const fn (i32) void) void {
        for (self.items.items) |item| f(item);
    }

    // ---- Functional Operations ----

    /// Returns a new stack with only elements satisfying the predicate.
    pub fn select(self: *const I32ArrayStack, predicate: *const fn (i32) bool) I32ArrayStack {
        var result = init(self.config.base);
        for (self.items.items) |item| {
            if (predicate(item)) result.push(item);
        }
        return result;
    }

    /// Returns a new stack with elements NOT satisfying the predicate.
    pub fn reject(self: *const I32ArrayStack, predicate: *const fn (i32) bool) I32ArrayStack {
        var result = init(self.config.base);
        for (self.items.items) |item| {
            if (!predicate(item)) result.push(item);
        }
        return result;
    }

    /// Returns the first element satisfying the predicate, or null.
    pub fn detect(self: *const I32ArrayStack, predicate: *const fn (i32) bool) ?i32 {
        for (self.items.items) |item| {
            if (predicate(item)) return item;
        }
        return null;
    }

    pub fn noneSatisfy(self: *const I32ArrayStack, predicate: *const fn (i32) bool) bool {
        for (self.items.items) |item| {
            if (predicate(item)) return false;
        }
        return true;
    }

    pub fn count(self: *const I32ArrayStack, predicate: *const fn (i32) bool) usize {
        var c: usize = 0;
        for (self.items.items) |item| {
            if (predicate(item)) c += 1;
        }
        return c;
    }

    pub fn injectInto(self: *const I32ArrayStack, initial: i32, f: *const fn (i32, i32) i32) i32 {
        var acc = initial;
        for (self.items.items) |item| acc = f(acc, item);
        return acc;
    }

    // ---- Conversion ----

    pub fn toSlice(self: *const I32ArrayStack) []const i32 {
        return self.items.items;
    }

    pub fn toImmutable(self: *const I32ArrayStack) @import("../immutable/immutable_i32_array_stack.zig").ImmutableI32ArrayStack {
        return @import("../immutable/immutable_i32_array_stack.zig").ImmutableI32ArrayStack.fromMutable(self.config.base, self);
    }

    // ---- Fluent API ----

    pub fn with(self: *I32ArrayStack, value: i32) *I32ArrayStack {
        self.push(value);
        return self;
    }

    pub fn withAll(self: *I32ArrayStack, values: []const i32) *I32ArrayStack {
        for (values) |val| self.push(val);
        return self;
    }

    // ---- Formatting ----

    /// Formats as "[top, ..., bottom]" (top-to-bottom order).
    pub fn format(self: *const I32ArrayStack, comptime _: []const u8, _: std.fmt.FormatOptions, writer: anytype) !void {
        try writer.writeAll("[");
        var i = self.items.items.len;
        var first = true;
        while (i > 0) {
            i -= 1;
            if (!first) try writer.writeAll(", ");
            try std.fmt.formatType(self.items.items[i], "", .{}, writer, 0);
            first = false;
        }
        try writer.writeAll("]");
    }

    // ---- Equality ----

    pub fn eql(self: *const I32ArrayStack, other: *const I32ArrayStack) bool {
        if (self.items.items.len != other.items.items.len) return false;
        for (self.items.items, other.items.items) |a, b| {
            if (!(a == b)) return false;
        }
        return true;
    }
};

test "I32ArrayStack: push peek pop" {
    var stack = I32ArrayStack.init(std.testing.allocator);
    defer stack.deinit();
    stack.push(1);
    stack.push(2);
    stack.push(3);
    try std.testing.expectEqual(@as(usize, 3), stack.len());
    try std.testing.expectEqual(@as(?i32, 3), stack.peek());
    try std.testing.expectEqual(@as(?i32, 3), stack.pop());
    try std.testing.expectEqual(@as(usize, 2), stack.len());
}

test "I32ArrayStack: pop empty" {
    var stack = I32ArrayStack.init(std.testing.allocator);
    defer stack.deinit();
    try std.testing.expectEqual(@as(?i32, null), stack.pop());
    try std.testing.expectEqual(@as(?i32, null), stack.peek());
}

test "I32ArrayStack: LIFO order" {
    var stack = I32ArrayStack.init(std.testing.allocator);
    defer stack.deinit();
    stack.push(1);
    stack.push(2);
    stack.push(3);
    try std.testing.expectEqual(@as(?i32, 3), stack.pop());
    try std.testing.expectEqual(@as(?i32, 2), stack.pop());
    try std.testing.expectEqual(@as(?i32, 1), stack.pop());
}

test "I32ArrayStack: contains" {
    var stack = I32ArrayStack.init(std.testing.allocator);
    defer stack.deinit();
    stack.push(1);
    try std.testing.expect(stack.contains(1));
    try std.testing.expect(!stack.contains(3));
}

test "I32ArrayStack: clear" {
    var stack = I32ArrayStack.of(std.testing.allocator, &[_]i32{1});
    defer stack.deinit();
    stack.clear();
    try std.testing.expect(stack.isEmpty());
}

test "I32ArrayStack: eql" {
    var s1 = I32ArrayStack.of(std.testing.allocator, &[_]i32{ 1, 2 });
    defer s1.deinit();
    var s2 = I32ArrayStack.of(std.testing.allocator, &[_]i32{ 1, 2 });
    defer s2.deinit();
    var s3 = I32ArrayStack.of(std.testing.allocator, &[_]i32{1});
    defer s3.deinit();
    try std.testing.expect(s1.eql(&s2));
    try std.testing.expect(!s1.eql(&s3));
}

test "I32ArrayStack: select and reject" {
    var stack = I32ArrayStack.of(std.testing.allocator, &[_]i32{ 1, 2, 3 });
    defer stack.deinit();
    var sel = stack.select(struct {
        fn f(val: i32) bool {
            return val > 1;
        }
    }.f);
    defer sel.deinit();
    try std.testing.expectEqual(@as(usize, 2), sel.len());
}

test "I32ArrayStack: toImmutable" {
    var stack = I32ArrayStack.of(std.testing.allocator, &[_]i32{ 1, 2 });
    defer stack.deinit();
    var imm = stack.toImmutable();
    defer imm.deinit();
    try std.testing.expectEqual(@as(usize, 2), imm.len());
    stack.push(3);
    try std.testing.expectEqual(@as(usize, 2), imm.len());
}

test "I32ArrayStack: fluent with" {
    var stack = I32ArrayStack.init(std.testing.allocator);
    defer stack.deinit();
    _ = stack.with(1).with(2);
    try std.testing.expectEqual(@as(usize, 2), stack.len());
}

test "I32ArrayStack: ensureUnusedCapacity reserves and subsequent push does not reallocate" {
    var stack = I32ArrayStack.init(std.testing.allocator);
    defer stack.deinit();
    try stack.ensureUnusedCapacity(10);
    const reserved = stack.items.capacity;
    try std.testing.expect(reserved >= 10);
    stack.push(1);
    stack.push(2);
    stack.push(3);
    try std.testing.expectEqual(reserved, stack.items.capacity);
}

test "I32ArrayStack: ensureTotalCapacity sets minimum capacity" {
    var stack = I32ArrayStack.init(std.testing.allocator);
    defer stack.deinit();
    try stack.ensureTotalCapacity(64);
    try std.testing.expect(stack.items.capacity >= 64);
}

test "I32ArrayStack: ensureUnusedCapacity propagates allocator error" {
    // fail_index = 0: Stack.init doesn't allocate (backed by ArrayList),
    // so the first alloc (ensureUnusedCapacity grow) fails immediately.
    var failing = std.testing.FailingAllocator.init(std.testing.allocator, .{ .fail_index = 0 });
    var stack = I32ArrayStack.initWithConfig(AllocatorConfig.init(failing.allocator()));
    defer stack.deinit();
    try std.testing.expectError(error.OutOfMemory, stack.ensureUnusedCapacity(1024));
}
